import type { Category } from './topics'

type Raw = [name: string, hook: string]

// Categories added for the Attic, each aimed at a facet of openness that the
// original library under-fed: wonder at scale, the body, film, craft, inner life,
// taste, place, moral imagination, futures, the uncanny, and play.
export const ATTIC_TOPICS: Partial<Record<Category, Raw[]>> = {
  'Cosmos & Space': [
    ["Black Holes", "Regions where gravity is so strong that not even light escapes; the first image of one was released in 2019."],
    ["The Golden Record", "Voyager carries a gold-plated record of greetings, music and sounds of Earth, in case anyone ever finds it."],
    ["Light-Years and Lookback Time", "The night sky is a museum: you see each star as it was when its light set out."],
    ["Europa’s Hidden Ocean", "Under the ice of Jupiter’s moon may be more liquid water than in all of Earth’s oceans."],
    ["Enceladus’ Geysers", "Saturn’s small moon sprays jets of water from a subsurface ocean out into space."],
    ["Olympus Mons", "The largest volcano known in the solar system, on Mars, is roughly two and a half times the height of Everest."],
    ["The Oort Cloud", "A hypothesised shell of icy bodies so far out it may reach a good fraction of the way to the nearest star."],
    ["The Overview Effect", "Many astronauts report a lasting shift in perspective after seeing Earth whole from orbit."],
    ["Fast Radio Bursts", "Millisecond flashes of radio energy from distant galaxies, first spotted in 2007."],
    ["The Great Attractor", "Our galaxy and its neighbours are drifting toward a gravitational anomaly hidden behind the Milky Way’s glare."],
    ["Tidal Locking", "The Moon always shows Earth the same face because its rotation matches its orbit."],
    ["The Lagrange Points", "Five spots where gravity balances so a small object can park near two big ones; the James Webb telescope sits near one."],
    ["Space Debris and Kessler Syndrome", "Collisions in orbit could create a cascade of debris that makes some orbits unusable."],
    ["The Apollo 13 Rescue", "Engineers improvised a fix for the carbon dioxide filters using parts already on board."],
    ["Zero Gravity and the Body", "In orbit, astronauts lose bone density and grow slightly taller as their spines stretch."],
    ["The Interstellar Visitor ‘Oumuamua", "In 2017 an object from another star system tumbled through ours, oddly shaped and briefly speeding up."],
    ["Auroras", "Charged particles from the Sun hit the upper atmosphere and make the sky glow green, red and purple."],
    ["Solar Eclipses", "By coincidence the Sun is about 400 times wider than the Moon and also about 400 times farther away."],
    ["The Andromeda Collision", "Our galaxy and Andromeda are approaching each other and may merge in several billion years."],
    ["Rogue Planets", "Worlds that drift through the galaxy with no star at all."],
    ["Hot Jupiters", "Gas giants that orbit their stars in just a few days, upending old ideas about how solar systems form."],
    ["Venus", "Its surface is hot enough to melt lead, and a day there is longer than its year."],
    ["The Sun’s Corona", "The Sun’s outer atmosphere is far hotter than its visible surface, and why is still being worked out."],
    ["The Arecibo Message", "In 1974 a radio dish beamed a pixelated picture of humans and DNA toward a star cluster 25,000 light-years away."],
    ["Space Elevators", "A cable from the equator to orbit sounds absurd, but the physics only demands an impossibly strong material."],
    ["Generation Ships", "Starships whose crews would be born, live and die on the journey between stars."],
    ["The Kardashev Scale", "A way to rank civilisations by how much energy they harness: a planet, a star, a galaxy."],
    ["Dyson Spheres", "Freeman Dyson suggested that advanced civilisations might wrap their star in collectors, glowing in infrared."],
    ["Meteorites", "Some rocks on Earth are older than the Earth itself, leftovers from the birth of the solar system."],
    ["The Tunguska Event", "In 1908 a blast flattened about 80 million trees in Siberia, likely from an exploding space rock."],
    ["The Chandrasekhar Limit", "Above about 1.4 solar masses a white dwarf cannot hold itself up and collapses."],
    ["Moon Illusion", "The Moon looks bigger near the horizon, though its size in the sky barely changes."],
    ["Star Names", "Many bright stars, like Betelgeuse, Aldebaran and Altair, carry Arabic names from medieval astronomers."],
    ["Light Pollution", "Most people in cities can no longer see the Milky Way."],
    ["The Goldilocks Zone", "The band around a star where a planet could be warm enough, but not too warm, for liquid water."],
    ["Jupiter’s Great Red Spot", "A storm wider than Earth that has been raging for at least a century and a half."],
    ["Titan", "Saturn’s largest moon has a thick atmosphere, methane rain and lakes of liquid hydrocarbons."],
    ["Io", "Jupiter’s moon Io is the most volcanically active world known, squeezed and heated by tides."],
    ["Comets", "Icy leftovers from the solar system’s birth; their tails always point away from the Sun."],
    ["Halley’s Comet", "Visible from Earth roughly every 76 years; it is next due back in 2061."],
    ["The Voyager Probes", "Launched in 1977, both have now crossed into interstellar space and still send faint signals home."],
    ["Planet Nine", "Some astronomers think an unseen planet far beyond Neptune is tugging on distant icy bodies."],
    ["Charon", "Pluto’s moon is so large that the pair orbit a point in the empty space between them."],
    ["Red Dwarfs", "Most stars are small, dim red dwarfs that can burn for trillions of years."],
    ["White Dwarfs", "The Sun will end as a white dwarf: a dense, Earth-sized ember slowly cooling."],
    ["Betelgeuse", "The red supergiant in Orion dimmed dramatically in 2019–20; one day it will explode."],
    ["Magnetars", "Neutron stars with the strongest magnetic fields known in the universe."],
    ["Quasars", "Some galaxy cores, powered by feeding black holes, outshine all of their galaxy’s stars."],
    ["Sagittarius A*", "The black hole at the centre of our galaxy weighs about four million Suns; it was imaged in 2022."],
    ["The Observable Universe", "Because space has expanded, its edge is now about 46 billion light-years away in every direction."],
    ["Cosmic Rays", "In 1991 a single particle from space hit Earth carrying the energy of a well-thrown baseball."],
    ["Spacewalks", "Alexei Leonov made the first spacewalk in 1965, and his suit ballooned so much he struggled to get back inside."],
  ],

  'The Body & Medicine': [
    ["The Microbiome", "Your body hosts trillions of microbes, roughly as many as your own cells."],
    ["The Vagus Nerve", "A long nerve that wanders from brainstem to gut and helps slow the heart when you breathe out."],
    ["Phantom Limbs", "Many amputees still feel the missing limb, and mirror boxes can ease the pain."],
    ["Proprioception", "Your ‘sixth sense’ knows where your limbs are with your eyes closed."],
    ["Anaesthesia", "Before the 1840s, surgery was done on people who were wide awake; speed was a surgeon’s main skill."],
    ["Handwashing and Semmelweis", "Ignaz Semmelweis cut deaths on a maternity ward by making doctors wash their hands, and was mocked for it."],
    ["Henrietta Lacks", "Cells taken from her without consent in 1951 became the HeLa line used in countless discoveries."],
    ["Sleep and the Glymphatic System", "During sleep the brain appears to flush out waste through fluid channels."],
    ["Fascia", "A web of connective tissue wraps every muscle and organ, and was long ignored in anatomy classes."],
    ["Taste Buds", "They renew themselves roughly every week or two."],
    ["The Enteric Nervous System", "Your gut contains hundreds of millions of neurons and can work largely on its own."],
    ["Stem Cells", "Cells that can become many other cell types, and the hope behind regenerative medicine."],
    ["CRISPR Gene Editing", "A bacterial defence system became a tool to edit DNA with precision."],
    ["Organ Transplants", "The first successful kidney transplant, in 1954, was between identical twins."],
    ["Blood Types", "Karl Landsteiner discovered the ABO groups in 1901, making safe transfusions possible."],
    ["The Heart’s Pacemaker", "A small knot of cells, the sinoatrial node, sets your heartbeat without any instruction from the brain."],
    ["Fever", "A raised temperature is often the body’s deliberate tactic against infection."],
    ["Hiccups", "A reflex spasm of the diaphragm that may be left over from our aquatic ancestors."],
    ["Goosebumps", "A remnant of the reflex that makes animals’ fur stand up to look bigger or stay warm."],
    ["Mirror Neurons", "Some neurons fire both when you act and when you watch someone else act, though their role is debated."],
    ["The Blind Spot", "Each eye has a gap where the optic nerve leaves, and your brain quietly fills it in."],
    ["Bone Remodelling", "Your skeleton is constantly broken down and rebuilt, replacing itself over roughly a decade."],
    ["The Lymphatic System", "A second circulatory network that drains fluid and carries immune cells."],
    ["Hormesis", "Small doses of stress, like cold, heat or exercise, can make the body stronger."],
    ["Muscle Memory", "Skills move into deeper brain structures with practice, which is why you never forget how to ride a bike."],
    ["The Hygiene Hypothesis", "Too little early exposure to microbes may make immune systems more prone to allergies."],
    ["Pain", "Pain is produced by the brain, not simply sent from the injury, which is why the same wound can hurt differently."],
    ["Laughter", "We laugh far more in company than alone, and laughter is contagious."],
    ["Tears", "Emotional tears differ in composition from the tears that wash out dust."],
    ["The Appendix", "Once called useless, it may be a safe house for helpful gut bacteria."],
    ["Trepanation", "Prehistoric people drilled holes in skulls, and some patients survived and healed."],
    ["The Four Humours", "For two thousand years medicine tried to balance blood, phlegm, yellow bile and black bile."],
    ["John Snow and Cholera", "Mapping deaths in 1854 London led him to a contaminated water pump on Broad Street."],
    ["The Hippocratic Oath", "Doctors have sworn versions of it for over two thousand years."],
    ["Blue Zones", "Places like Okinawa and Sardinia are famous for unusually long-lived people."],
    ["Interoception", "The sense of your body’s inner state, like hunger, heartbeat and breath, is linked to how you feel emotions."],
    ["The Diving Reflex", "Cold water on the face slows your heart and saves oxygen, a reflex shared with seals."],
    ["Yawning", "Why we yawn isn’t settled, but it is contagious even between people and dogs."],
    ["Fingerprints", "Even identical twins have different fingerprints."],
    ["Regeneration", "The human liver can regrow from a portion of its original size."],
    ["Prosthetics", "Modern bionic limbs can be controlled by signals from the user’s own muscles."],
    ["Florence Nightingale’s Charts", "She used pioneering diagrams to show that more soldiers died of disease than wounds."],
    ["The Fight-or-Flight Response", "Within seconds of a threat, adrenaline speeds your heart and sharpens your senses."],
    ["Immune Memory", "Memory cells can remember an infection for decades, the principle behind vaccines."],
    ["Red Blood Cells", "They have no nucleus and live about 120 days; your body makes millions every second."],
    ["The Skin", "Your largest organ is constantly shedding and renewing its outer layers."],
    ["The Cochlea", "A snail-shaped organ in the inner ear turns vibrations into nerve signals using tiny hair cells."],
    ["The Sense of Smell", "Smell has a direct line to brain areas tied to memory and emotion."],
    ["Insulin", "Its discovery in 1921 turned type 1 diabetes from a death sentence into a manageable condition."],
    ["The Human Hand", "Each hand has 27 bones, and the opposable thumb lets us grip and make tools."],
  ],

  'Cinema & Film': [
    ["The Kuleshov Effect", "The same blank face reads as hunger, grief or desire depending on the shot cut next to it."],
    ["A Trip to the Moon", "Georges Méliès, a stage magician, made one of the first sci-fi films in 1902."],
    ["The Arrival of a Train", "A legend says early audiences ran from the Lumière brothers’ train; it is probably exaggerated."],
    ["German Expressionism", "The Cabinet of Dr. Caligari painted shadows and twisted sets to show a disturbed mind."],
    ["Film Noir", "Shadowy American crime films of the 1940s and 50s, named by French critics."],
    ["Italian Neorealism", "After the war, directors shot on real streets with non-actors, as in Bicycle Thieves."],
    ["The French New Wave", "Young critics like Godard and Truffaut picked up cameras and broke the rules of continuity."],
    ["Akira Kurosawa", "Seven Samurai and Rashomon reshaped how stories are told around the world."],
    ["The Rashomon Effect", "Four witnesses tell four incompatible versions of the same event."],
    ["Studio Ghibli", "Hand-drawn worlds like Spirited Away and My Neighbor Totoro, made with near-obsessive care."],
    ["Andrei Tarkovsky", "Long takes, rain and memory; he called filmmaking ‘sculpting in time’."],
    ["Satyajit Ray", "His Apu Trilogy, made on a shoestring in Bengal, became a landmark of world cinema."],
    ["Bollywood", "Mumbai’s film industry is one of the most prolific in the world, famous for song-and-dance numbers."],
    ["Nollywood", "Nigeria’s film industry grew from cheap video productions into one of the largest by volume."],
    ["Hitchcock’s Suspense", "Show the audience the bomb under the table, and an ordinary chat becomes unbearable."],
    ["The MacGuffin", "The object everyone chases, which barely matters in itself."],
    ["Dolly Zoom", "Moving the camera while zooming the other way makes the world seem to stretch, as in Vertigo."],
    ["The Long Take", "A single unbroken shot, like the opening of Touch of Evil, makes time feel real."],
    ["Montage", "Sergei Eisenstein argued that meaning comes from the collision of two shots."],
    ["The 180-Degree Rule", "Keep the camera on one side of the action, or the audience loses track of who is where."],
    ["Foley Art", "The footsteps, punches and rustles in films are mostly recorded later by artists on a sound stage."],
    ["Stop-Motion", "Every frame of films like Coraline is a tiny model moved by hand."],
    ["Practical Effects", "Miniatures, puppets and real explosions often age better than early CGI."],
    ["The Wilhelm Scream", "A stock scream recorded in the early 1950s has been reused in hundreds of films."],
    ["Colour Grading", "The teal-and-orange look of many blockbusters is a deliberate choice made after shooting."],
    ["Aspect Ratios", "Widescreen formats spread in the 1950s partly as cinema’s answer to television."],
    ["The Silent Era", "Silent films were rarely silent: live musicians or organs played along."],
    ["The Jazz Singer", "In 1927 sound films arrived, and many silent-film careers ended."],
    ["The Hays Code", "From the 1930s to the 1960s, Hollywood censored itself with strict rules on what could be shown."],
    ["Documentary", "Nanook of the North (1922) blurred real life and staging from the very start."],
    ["Dogme 95", "A Danish manifesto banned film lighting, props and genre conventions to strip cinema back to truth."],
    ["Charlie Chaplin", "The Tramp made him one of the most recognisable people on Earth in the silent era."],
    ["Buster Keaton", "The ‘Great Stone Face’ performed staggering stunts himself, including a house front falling around him."],
    ["Agnès Varda", "A photographer turned filmmaker whose playful documentaries made the personal into art."],
    ["Wong Kar-wai", "In the Mood for Love turns longing into colour, slow motion and repeated music."],
    ["Iranian Cinema", "Directors like Abbas Kiarostami made profound films with children, cars and long conversations."],
    ["Korean Cinema", "Parasite became the first film not in English to win the Oscar for Best Picture."],
    ["Spaghetti Westerns", "Italian-made westerns, shot partly in Spain, reinvented the genre with Ennio Morricone’s scores."],
    ["The Film Score", "John Williams’ two notes for Jaws made an unseen shark terrifying."],
    ["Mise-en-scène", "Everything placed in the frame, from furniture to light, tells part of the story."],
    ["Unreliable Narrators on Screen", "Films like Memento and Fight Club make the audience doubt what they have seen."],
    ["The Bechdel Test", "Do two named women talk to each other about something other than a man? Many films fail."],
    ["The Three-Act Structure", "Setup, confrontation, resolution: the skeleton under most Hollywood screenplays."],
    ["Cinema Paradiso", "A love letter to a village cinema, and to how films shape a childhood."],
    ["The Criterion Collection", "A curated library of important classic and contemporary films."],
    ["Film Festivals", "Cannes, Venice and Sundance make or break careers in a week."],
    ["Anime", "Japanese animation ranges from Astro Boy to Akira to Your Name."],
    ["Pixar’s Story Rules", "‘Once upon a time... every day... one day... because of that...’ builds a story from cause and effect."],
    ["The Uncanny Valley on Screen", "Nearly human CGI faces can feel creepier than cartoons."],
    ["Slow Cinema", "Films that linger, inviting attention rather than delivering plot."],
  ],

  'Crafts & Making': [
    ["Wabi-Sabi in Craft", "A pot that is slightly uneven can feel more alive than a perfect one."],
    ["Bookbinding", "Folding, sewing and gluing paper by hand turns loose pages into an object meant to last centuries."],
    ["Letterpress", "Each letter is a piece of metal or wood, set by hand and pressed into paper."],
    ["Calligraphy", "Arabic, Chinese and Western calligraphy each treat writing as an art of breath and gesture."],
    ["Woodworking Joints", "Dovetails and mortise-and-tenon joints can hold furniture together without nails or glue."],
    ["Blacksmithing", "Heat, hammer and quench: a blacksmith reads the colour of hot steel to judge temperature."],
    ["Damascus Steel", "Old blades with watery patterns were made from wootz steel whose exact method was later lost."],
    ["Glassblowing", "Molten glass is gathered on a pipe and shaped with breath and gravity."],
    ["Pottery on the Wheel", "Centring the clay is the first and hardest skill; everything wobbles until it’s centred."],
    ["Raku Firing", "Pots are pulled red-hot from the kiln and smoked, so crackles and colours are partly left to chance."],
    ["Weaving", "The Jacquard loom’s punch cards inspired early computing."],
    ["Natural Dyes", "Indigo, madder and cochineal coloured the world’s clothes for thousands of years."],
    ["Tyrian Purple", "Thousands of sea snails were needed for a small amount of this ancient dye, worn by emperors."],
    ["Knitting as Code", "A knitting pattern is an algorithm, and a few stitches combine into endless textures."],
    ["Quilting", "Gee’s Bend quilts from Alabama hang in art museums."],
    ["Sashiko", "Japanese running-stitch embroidery began as a way to mend and strengthen work clothes."],
    ["Visible Mending", "Darning holes in bright thread treats repair as decoration, not shame."],
    ["Origami", "Paper folding inspired the folding of space telescope mirrors and airbags."],
    ["Papermaking", "Paper was invented in China around 2,000 years ago and reached Europe via the Islamic world."],
    ["Marbled Paper", "Ink floated on thickened water is swirled and lifted onto paper; no two sheets are alike."],
    ["Leatherworking", "Saddle stitching uses two needles on one thread, so a single broken stitch won’t unravel the seam."],
    ["Basket Weaving", "Some of the oldest crafts on Earth; a tight basket can even hold water."],
    ["Mosaic", "Thousands of small pieces of stone or glass make one image, from Roman floors to Byzantine domes."],
    ["Bonsai", "Growing a tree in miniature takes decades of patient pruning."],
    ["Sourdough Starters", "A jar of flour and water captures wild yeasts; some starters are said to be over a century old."],
    ["Fermentation Crafts", "Kimchi, miso and kombucha are made by microbes you tend like a garden."],
    ["Luthiers", "Violin makers still study how Stradivari’s instruments were made."],
    ["Watchmaking", "A mechanical watch can contain hundreds of tiny parts working without a battery."],
    ["Shoemaking", "A bespoke shoe begins with a wooden ‘last’ carved to the shape of one person’s foot."],
    ["Hand Tools vs Power Tools", "Working slowly by hand changes what you notice about the material."],
    ["The Shokunin Spirit", "A Japanese ideal of the craftsperson who spends a lifetime perfecting one thing."],
    ["The Arts and Crafts Movement", "William Morris argued that ordinary things should be beautiful and made with joy."],
    ["Repair Cafés", "Volunteers help neighbours fix toasters, clothes and bikes instead of throwing them away."],
    ["Lacemaking", "Bobbin lace was a valuable luxury, with intricate patterns made thread by thread."],
    ["Embroidery", "The Bayeux Tapestry is actually embroidery, about 70 metres long."],
    ["Candle Making", "Beeswax candles were once a luxury; most people burned smoky tallow."],
    ["Soap Making", "Mixing fat and lye triggers a chemical reaction called saponification."],
    ["Printmaking", "Woodcuts, etchings and linocuts let one image become many."],
    ["Carving Spoons", "Green woodworkers carve spoons from fresh wood because it cuts like butter."],
    ["Making a Knife", "Grinding a bevel by hand teaches what ‘sharp’ really means."],
    ["Maker Spaces", "Shared workshops with lasers, lathes and 3D printers make making social."],
    ["Mud Brick", "Adobe has housed people for millennia, and some mud-brick cities are still lived in."],
    ["Thatching", "A well-made thatched roof can last for decades."],
    ["Boat Building", "Viking ships were built ‘clinker’ style, with overlapping planks that let the hull flex in waves."],
    ["Tinkering", "Taking things apart to see how they work is how many engineers start."],
    ["The Craftsman’s Hours", "Mastery is often linked to thousands of hours of deliberate practice."],
    ["Shibori", "A Japanese way of folding, twisting and binding cloth before dyeing, often with indigo."],
    ["Batik", "Wax drawn on cloth resists the dye; Indonesian batik is on UNESCO’s heritage list."],
    ["Persian Carpets", "Fine hand-knotted rugs can contain hundreds of knots per square inch and take a long time to make."],
    ["Cooperage", "Barrel makers bend wooden staves with heat and hold them with hoops, with no glue."],
  ],

  'Emotions & Inner Life': [
    ["Emotional Granularity", "People who name feelings precisely, like irritated, wistful or uneasy, may handle them better."],
    ["Awe", "Feeling small in front of something vast can make people more generous and less self-focused."],
    ["Sonder", "A coined word for realising that every passer-by has a life as vivid and complex as yours."],
    ["Schadenfreude", "German for pleasure at someone else’s misfortune, which most people feel and few admit."],
    ["Mono no Aware", "A Japanese sensitivity to the passing of things, like cherry blossoms falling."],
    ["Ambivalence", "Feeling two opposing things at once is normal, not a sign that something is wrong."],
    ["Nostalgia", "Once considered a disease of homesick soldiers, it now appears to boost a sense of meaning."],
    ["Boredom", "Boredom may be a signal to look for something more meaningful, and it can spark creativity."],
    ["Curiosity", "Curiosity has been linked to the brain’s reward systems and can make information stick better."],
    ["Shame vs Guilt", "Guilt says ‘I did something bad’; shame says ‘I am bad’, and they push us in different directions."],
    ["Envy as Information", "Envy can point to what you secretly want for yourself."],
    ["Anger’s Message", "Anger often signals that a boundary or value has been crossed."],
    ["Grief", "There is no single fixed sequence of stages; grief comes in waves."],
    ["Anticipatory Grief", "Mourning a loss before it fully happens."],
    ["The Affect Heuristic", "How we feel about something quietly shapes how risky or good we judge it to be."],
    ["Flow", "Losing track of time in a task that is challenging but within reach."],
    ["Gratitude", "Writing down good things has been linked in studies to better well-being."],
    ["Vulnerability", "Brené Brown argues that being seen, uncertainty and all, is the birthplace of connection."],
    ["Loneliness", "Loneliness is a feeling, not a head count; you can be lonely in a crowd."],
    ["Solitude", "Chosen time alone can restore rather than isolate."],
    ["Compassion vs Empathy", "Feeling someone’s pain can exhaust you; wishing them well and acting can sustain you."],
    ["Self-Compassion", "Talking to yourself as you would to a friend often works better than self-criticism."],
    ["Emotional Suppression", "Pushing feelings down can leave you more physiologically stressed, not less."],
    ["Reappraisal", "Seeing the same situation in another light can change how it feels."],
    ["Elevation", "The warm, uplifting feeling of seeing someone do something good."],
    ["Kama Muta", "Being moved: the tears and chills when you witness sudden closeness or love."],
    ["Frisson", "Music can give some people chills down the spine at certain moments."],
    ["Melancholy", "Many thinkers have treated sadness as a source of depth and creativity."],
    ["Joy vs Happiness", "Joy can arrive as a sudden surge in the middle of a hard life."],
    ["Hope", "Hope involves goals, pathways to them and the belief that you can move along those pathways."],
    ["Fear of Missing Out", "FOMO feeds on seeing other people’s best moments, curated."],
    ["Jealousy", "Jealousy fears losing what you have; envy wants what someone else has."],
    ["Pride", "Pride in effort tends to motivate, while pride in innate talent can make people fragile."],
    ["Embarrassment", "Blushing may signal to others that you care about the social rules you broke."],
    ["Contentment", "A quiet emotion that rarely makes headlines but sustains a life."],
    ["The Inner Critic", "The voice in your head that judges you was often learned from somewhere."],
    ["Inner Speech", "Some people think in words, some in images, and some report hardly any inner voice at all."],
    ["Daydreaming", "The mind wanders a large part of waking life, often planning, imagining and remembering."],
    ["Dreams", "We forget most dreams within minutes of waking unless we write them down."],
    ["Lucid Dreaming", "Some people can realise they are dreaming and steer the dream."],
    ["Journaling", "Writing about hard experiences for a few days has been linked to better health in some studies."],
    ["Emotional Labour", "Arlie Hochschild studied flight attendants paid to manage their feelings with a smile."],
    ["Alexithymia", "Some people struggle to identify or describe their own emotions."],
    ["Feeling Tones in Buddhism", "Vedanā: every experience arrives as pleasant, unpleasant or neutral before we react."],
    ["Tears of Joy", "We sometimes cry when happy, a puzzle researchers still debate."],
    ["Psychological Safety", "Teams that feel safe to admit mistakes tend to learn faster."],
    ["Fernweh", "A German word for longing for far-off places: the opposite of homesickness."],
    ["Mudita", "A Buddhist idea: joy at someone else’s good fortune, the antidote to envy."],
    ["Anxiety Reappraisal", "Telling yourself ‘I’m excited’ rather than ‘calm down’ can help performance under pressure."],
    ["Co-Regulation", "Children learn to calm down by borrowing the calm of a steady adult, and so do grown-ups."],
    ["Waldeinsamkeit", "A German word for the peaceful feeling of being alone in the woods."],
  ],

  'Food & Cuisine': [
    ["Umami", "Kikunae Ikeda identified the savoury fifth taste in kombu broth in 1908."],
    ["The Maillard Reaction", "Browning bread, steak and coffee creates hundreds of flavour compounds."],
    ["Fermentation", "Cheese, bread, wine, soy sauce and kimchi are all foods partly made by microbes."],
    ["Spice Routes", "Pepper, cloves and nutmeg once shaped empires, wars and maps."],
    ["Chilli Peppers", "Native to the Americas, chillies reached India, Thailand and Korea only after 1492."],
    ["The Columbian Exchange of Food", "Tomatoes in Italy, potatoes in Ireland and maize in Africa all came after Columbus."],
    ["Sushi", "It began as a way of preserving fish in fermented rice, which was thrown away."],
    ["Japanese Kaiseki", "A multi-course meal that follows the seasons, in which the plates matter as much as the food."],
    ["Mole", "Some Mexican moles combine chillies, chocolate, spices and seeds, with dozens of ingredients."],
    ["Injera", "Ethiopian sourdough flatbread made from teff is plate, spoon and food at once."],
    ["Dim Sum", "Small dishes with tea in Cantonese teahouses; the name is often translated as ‘touch the heart’."],
    ["Coffee’s Journey", "From Ethiopian highlands to Yemeni Sufis to Ottoman coffee houses to everywhere."],
    ["Tea Ceremonies", "The Japanese way of tea turns making a drink into a meditation on hospitality."],
    ["Chocolate", "The Maya and Aztecs drank cacao bitter and spiced; sugar came later in Europe."],
    ["Bread", "One of the oldest prepared foods, with evidence of baking from over 14,000 years ago."],
    ["Cheese", "There are more than a thousand cheeses made from basically the same few things: milk, salt, microbes and time."],
    ["Salt", "Salt was valuable enough to tax and to fight over; Gandhi’s 1930 Salt March challenged British rule."],
    ["Sugar and History", "The sugar trade drove plantation slavery in the Caribbean and Brazil."],
    ["Street Food", "From Bangkok’s night markets to Mexico City taco stands, some of the best food is cooked on the pavement."],
    ["Bento Boxes", "Japanese lunchboxes can be arranged as carefully as small artworks."],
    ["Thali", "An Indian platter that brings together several tastes in one meal."],
    ["Mezze", "Small shared dishes across the Eastern Mediterranean make eating a conversation."],
    ["Tapas", "Spanish bites eaten standing up, often hopping from bar to bar."],
    ["Fusion Cuisine", "Korean tacos and Peruvian Nikkei cuisine show what happens when food migrates."],
    ["Molecular Gastronomy", "Chefs use foams, gels and liquid nitrogen to make food surprising."],
    ["Nose-to-Tail Eating", "Using every part of the animal is old wisdom rebranded."],
    ["Foraging", "Wild garlic, nettles and mushrooms grow for free, if you know what you’re doing."],
    ["The Scoville Scale", "Measures chilli heat; the hottest peppers rate in the millions."],
    ["Bitter Tastes", "Many people learn to love bitter foods like coffee, beer and dark greens as they grow older."],
    ["Smell and Flavour", "Much of what we call taste is actually smell, which is why food tastes flat with a cold."],
    ["Feasts", "From harvest festivals to wedding banquets, big meals bind communities."],
    ["Slow Food", "A movement born in Italy to defend local food traditions against fast food."],
    ["The Potato", "Andean farmers domesticated the potato thousands of years ago and grew many varieties."],
    ["Rice", "Rice paddies have shaped landscapes, calendars and societies across Asia."],
    ["Olive Oil", "Some olive trees around the Mediterranean are thought to be well over a thousand years old."],
    ["Wine Terroir", "Soil, climate and slope give the same grape very different tastes."],
    ["Honey", "Honey can keep for an extremely long time because it is so dry and acidic."],
    ["Kimchi", "Korean families make huge batches together in autumn in a tradition called gimjang."],
    ["Pizza Napoletana", "The art of the Neapolitan pizzaiuolo is on UNESCO’s intangible heritage list."],
    ["Ramen", "A Chinese-inspired noodle soup became a Japanese obsession with countless regional styles."],
    ["Pho", "Vietnam’s noodle soup is often eaten for breakfast."],
    ["Jollof Rice", "West African countries argue fiercely over whose version is best."],
    ["Peruvian Ceviche", "Raw fish ‘cooked’ in lime juice; the acid changes the proteins without heat."],
    ["Cooking with Fire", "Richard Wrangham argues that cooking helped make us human by making food easier to digest."],
    ["The Michelin Guide", "A tyre company started a restaurant guide to get people driving more."],
    ["Mise en Place", "Chefs prepare and arrange every ingredient before cooking starts."],
    ["Eating with Hands", "In many cultures, eating with the hand is said to make food taste better."],
    ["Seaweed", "Japanese and Welsh cooks have long eaten seaweed, from nori to laverbread."],
    ["Saffron", "Each crocus flower gives just three threads, picked by hand; it is one of the costliest spices by weight."],
    ["Vanilla", "In 1841 Edmond Albius, an enslaved 12-year-old on Réunion, found a quick way to hand-pollinate vanilla orchids."],
  ],

  'Places & Geography': [
    ["The Atacama Desert", "Parts of it are among the driest places on Earth, and it is one of the best places to watch the stars."],
    ["Lake Baikal", "Holds about a fifth of the world’s unfrozen fresh surface water."],
    ["Salar de Uyuni", "The world’s largest salt flat in Bolivia becomes a giant mirror after rain."],
    ["Socotra", "An island off Yemen where many plants, like the dragon’s blood tree, grow nowhere else."],
    ["Svalbard", "An Arctic archipelago with a global seed vault and roughly as many polar bears as people."],
    ["The Silk Road Cities", "Samarkand, Bukhara and Kashgar were crossroads of goods, faiths and ideas."],
    ["Angkor", "The temple city in Cambodia once sat at the heart of a vast settlement."],
    ["Timbuktu", "Once a centre of scholarship with thousands of manuscripts, now a byword for remoteness."],
    ["Kyoto", "Over a thousand years as Japan’s imperial capital, with temples and gardens around every corner."],
    ["Istanbul", "A city on two continents, once Byzantium and Constantinople."],
    ["Varanasi", "One of the oldest continuously inhabited cities, where the dead are cremated on the Ganges."],
    ["Iceland", "Sitting on a rift between two tectonic plates, it is literally being pulled apart."],
    ["The Great Rift Valley", "East Africa is slowly splitting, and may one day form a new ocean."],
    ["Pangea", "All continents were once joined; Africa and South America still fit like puzzle pieces."],
    ["The Sahara’s Green Past", "Thousands of years ago the Sahara had lakes, hippos and grasslands."],
    ["Mount Everest", "It is still rising by a few millimetres each year as India pushes into Asia."],
    ["Chimborazo", "Because Earth bulges at the equator, its summit is the farthest point from Earth’s centre."],
    ["The Dead Sea", "So salty you float effortlessly, and its shore is the lowest land on Earth."],
    ["The Danakil Depression", "One of the hottest places on Earth, with acid pools in yellow, green and orange."],
    ["Antarctica", "A continent with no permanent residents, governed by an international treaty."],
    ["Greenland", "Its ice sheet is so heavy it presses the land beneath it below sea level."],
    ["Fjords", "Glaciers carved Norway’s coastline into deep, steep-sided inlets."],
    ["The Galápagos", "Darwin’s visit in 1835 helped plant the seeds of evolution by natural selection."],
    ["Madagascar", "Lemurs live in the wild only here."],
    ["Bhutan", "Bhutan measures progress partly with Gross National Happiness."],
    ["Mongolia", "One of the most sparsely populated countries, where many still live a nomadic life."],
    ["Tristan da Cunha", "One of the most remote inhabited islands on Earth, reached only by boat."],
    ["Point Nemo", "The spot in the ocean farthest from any land, where old spacecraft are deliberately crashed."],
    ["The International Date Line", "Cross it, and you jump a day forward or back."],
    ["Enclaves and Exclaves", "Baarle-Nassau and Baarle-Hertog have a border running through houses and cafés."],
    ["Map Projections", "The Mercator map makes Greenland look as big as Africa, which is about 14 times larger."],
    ["Cartography", "Every map is a choice about what to leave out."],
    ["The Ring of Fire", "Most of the world’s volcanoes and earthquakes circle the Pacific Ocean."],
    ["Monsoons", "Seasonal winds bring rains that farmers across South Asia depend on."],
    ["Deserts of Ice", "Antarctica counts as the world’s largest desert because so little snow falls."],
    ["The Nile", "It flows north for over 6,000 km through deserts that would be empty without it."],
    ["Rivers that Changed Course", "The Yellow River has shifted course many times, sometimes with catastrophic floods."],
    ["Mount Roraima", "A flat-topped tabletop mountain in South America that inspired The Lost World."],
    ["Zhangjiajie", "Sandstone pillars in China rise from mist and inspired Avatar’s floating mountains."],
    ["The Faroe Islands", "Grass-roofed houses on windswept cliffs in the North Atlantic."],
    ["Cappadocia", "People carved homes and churches into soft volcanic rock and even built underground cities."],
    ["Las Vegas’ Water", "A desert city that depends on the shrinking Colorado River."],
    ["Megacities", "Tokyo, Delhi and Shanghai each hold more people than many countries."],
    ["Ghost Towns", "Abandoned places like Pripyat or Kolmanskop slowly return to nature."],
    ["Lake Titicaca", "One of the highest large navigable lakes, where the Uros people live on floating islands of reeds."],
    ["Bagan", "Thousands of Buddhist temples and pagodas rise from a plain in Myanmar."],
    ["Ha Long Bay", "Limestone towers rise straight out of the sea in northern Vietnam."],
    ["Patagonia", "A wind-scoured land of glaciers and steppe at the bottom of the Americas."],
    ["Lalibela", "In Ethiopia, churches were carved downward into solid rock about 800 years ago."],
    ["The Door to Hell", "A gas crater in Turkmenistan has been burning since it was set alight, reportedly in 1971."],
  ],

  'Ethics & Dilemmas': [
    ["The Ship of Theseus in Ethics", "If your values change bit by bit, are you still bound by promises you made?"],
    ["Kant’s Categorical Imperative", "Act only in ways you’d want everyone to act, and never use people merely as tools."],
    ["Care Ethics", "Morality grows from relationships of care, not only abstract rules."],
    ["Animal Ethics", "Jeremy Bentham asked of animals not ‘can they reason?’ but ‘can they suffer?’"],
    ["Lying to the Murderer at the Door", "Kant argued you shouldn’t even lie to save a friend; most people disagree."],
    ["The Prisoner’s Dilemma in Life", "When trust is fragile, doing the selfish thing can leave everyone worse off."],
    ["Moral Circles", "Over history, many people have extended moral concern to more groups. Who is outside the circle today?"],
    ["Future Generations", "What do we owe people who don’t exist yet?"],
    ["Whistleblowing", "Loyalty to colleagues against duty to the public."],
    ["Civil Disobedience", "Thoreau, Gandhi and King broke laws they considered unjust, and accepted the consequences."],
    ["The Ring of Gyges", "Plato asked: would you still be just if you could turn invisible?"],
    ["Is-Ought Gap", "Hume noted you can’t derive what ought to be just from what is."],
    ["Double Effect", "Is it different to cause harm as a means, versus as a foreseen side effect?"],
    ["Consent", "What makes consent real: information, freedom and the ability to say no."],
    ["Privacy", "Is privacy a right, a preference, or something we trade away for convenience?"],
    ["AI Ethics", "Who is responsible when an algorithm makes a harmful decision?"],
    ["Bioethics", "Designer babies, organ markets and life extension raise questions that grow sharper every year."],
    ["The Ethics of Eating", "Every meal involves choices about animals, workers and the planet."],
    ["Lifeboat Ethics", "When there isn’t room for everyone, who decides?"],
    ["Promises", "Why does saying ‘I promise’ create an obligation that wasn’t there before?"],
    ["Forgiveness", "Does forgiving mean forgetting, excusing, or something else entirely?"],
    ["Revenge vs Justice", "Justice aims to repair or deter; revenge aims to make someone suffer."],
    ["Restorative Justice", "Bringing offenders and victims together to repair harm, not just punish it."],
    ["Moral Courage", "Doing what’s right when it costs you something."],
    ["The Bystander Problem", "Do you have a duty to help a stranger, or only not to harm them?"],
    ["Honesty vs Kindness", "When the truth would wound, which value wins?"],
    ["Loyalty", "Should you be loyal to friends even when they’re wrong?"],
    ["Moral Intuitions", "Jonathan Haidt argues we often feel first and reason second to justify the feeling."],
    ["Moral Foundations", "Care, fairness, loyalty, authority and sanctity weigh differently for different people."],
    ["Steelmanning", "Building the strongest version of the view you disagree with before you argue."],
    ["The Golden Rule", "Some version of ‘treat others as you’d want to be treated’ appears across many religions."],
    ["Ends and Means", "Can a good outcome justify a bad method?"],
    ["Dirty Hands", "Can a leader be right to do something wrong for the public good?"],
    ["Paternalism", "When is it right to stop people from harming themselves?"],
    ["The Ethics of Wealth", "Is there a point at which having more becomes a moral problem?"],
    ["Moral Progress", "Was the abolition of slavery a discovery, or a change in taste?"],
    ["Supererogation", "Some acts are good but not required: heroes go beyond duty."],
    ["Euthanasia", "Should people have the right to choose when they die?"],
    ["Free Speech", "Where does free expression end and harm begin?"],
    ["The Ticking Time Bomb", "If torture could stop a bomb, would it be justified? And what happens to a society that says yes?"],
    ["The Survival Lottery", "John Harris asked: if one person’s organs could save two, why not hold a lottery?"],
    ["Partiality", "Is it right to save your own child before two strangers?"],
    ["Desert and Talent", "Do people deserve rewards for talents they were simply born with?"],
    ["The Non-Identity Problem", "Derek Parfit: some choices decide who will exist, so who exactly is harmed by them?"],
    ["Doing vs Allowing", "Is letting someone die as bad as killing them?"],
    ["Collective Responsibility", "Are you responsible for what your country, company or ancestors did?"],
    ["Moral Dumbfounding", "People often insist something is wrong, then can’t say why when every reason is removed."],
    ["Duty to Rescue", "Some countries make it a legal duty to help a person in danger; others don’t."],
    ["White Lies", "‘I love the present’: harmless kindness, or a small erosion of trust?"],
    ["Moral Uncertainty", "How should you act when you aren’t sure which moral theory is right?"],
  ],

  'Futures & Speculation': [
    ["Speculative Design", "Designers build objects from possible futures to provoke debate today."],
    ["The Long Now Foundation", "Builders of a clock meant to tick for 10,000 years inside a mountain."],
    ["Futures Wheels", "Draw a change in the middle, then its consequences, then their consequences."],
    ["Scenario Planning", "Shell used scenarios to prepare for the 1970s oil shocks before they happened."],
    ["The Singularity", "A hypothetical point when technology accelerates beyond our ability to predict it."],
    ["Mind Uploading", "Could a mind be copied to a computer, and would it still be you?"],
    ["Longevity Research", "Scientists study whether ageing itself can be slowed down."],
    ["Cryonics", "Freezing bodies in the hope that future medicine can revive them."],
    ["Terraforming Mars", "Could we ever thicken Mars’ air and warm it enough to live there?"],
    ["Asteroid Mining", "Some asteroids contain huge amounts of metal."],
    ["Fusion Power", "Making a star in a bottle has been ‘thirty years away’ for a long time, but progress is real."],
    ["The Four-Day Week", "Trials in several countries have found productivity often holds steady."],
    ["Lab-Grown Meat", "Meat grown from animal cells, without raising and slaughtering animals."],
    ["Vertical Farming", "Growing crops in stacked layers indoors, under LEDs."],
    ["Smart Cities", "Sensors everywhere could make cities efficient, or turn them into surveillance machines."],
    ["Brain–Computer Interfaces", "Implants have let paralysed people move cursors and type with their thoughts."],
    ["Space Colonies", "Gerard O’Neill imagined giant rotating cylinders with farms and towns inside."],
    ["Climate Adaptation", "Floating houses in the Netherlands are designed to rise with floods."],
    ["Geoengineering", "Deliberately cooling the planet could help, or cause new problems."],
    ["De-extinction", "Scientists aim to bring back mammoth-like traits using elephant cells."],
    ["Post-Scarcity", "Star Trek imagines a society where material needs are met for everyone."],
    ["Utopias", "Thomas More coined ‘utopia’, a pun on ‘no place’ and ‘good place’."],
    ["Dystopias", "1984, Brave New World and The Handmaid’s Tale are warnings dressed as stories."],
    ["Retrofuturism", "Yesterday’s vision of tomorrow: jetpacks, flying cars and chrome robots."],
    ["Technological Unemployment", "Keynes predicted we’d work 15-hour weeks by now."],
    ["Digital Afterlives", "Chatbots trained on a dead person’s messages raise strange new questions about grief."],
    ["Seasteading", "Proposals for floating cities on the open ocean."],
    ["The Great Filter", "Maybe something stops most civilisations from spreading. Is it behind us or ahead?"],
    ["Existential Risk", "Risks that could end humanity or permanently cripple its future."],
    ["Longtermism", "The idea that positively influencing the long-term future is a key moral priority."],
    ["Biophilic Cities", "Singapore weaves plants into buildings and streets."],
    ["Robots in Care", "Japan is experimenting with robots in elder care."],
    ["Programmable Matter", "Materials that could change shape or properties on command."],
    ["Quantum Internet", "Networks sharing quantum states could make some communications far more secure."],
    ["Interstellar Probes", "Breakthrough Starshot proposes tiny light-sail probes pushed by lasers toward Alpha Centauri."],
    ["Future Languages", "How might English sound in 500 years? Chaucer’s English is already hard to read."],
    ["Time Capsules", "The Westinghouse capsule from 1939 is meant to be opened in the year 6939."],
    ["Nuclear Waste Warnings", "How do you warn people 10,000 years from now that a site is dangerous?"],
    ["Future Selves", "People who feel connected to their future selves tend to save more."],
    ["Hyperobjects", "Timothy Morton’s term for things like climate change that are too vast to see all at once."],
    ["Degrowth", "A movement questioning whether endless economic growth is possible or desirable."],
    ["The Kardashev Future", "If we harnessed all the Sun’s energy, what would we do with it?"],
    ["Speculative Fiction Prophecies", "Arthur C. Clarke described geostationary communications satellites back in 1945."],
    ["Space Tourism", "Private citizens now buy rides to the edge of space and beyond."],
    ["Digital Twins", "Virtual copies of factories, cities or even organs let people test changes before making them."],
    ["Autonomous Weapons", "Should a machine ever decide on its own to use lethal force?"],
    ["Personalised Medicine", "Treatments tailored to your genes, rather than to the average patient."],
    ["The Hydrogen Economy", "A fuel whose only exhaust is water, if it can be made cleanly and cheaply."],
    ["Desalination", "Turning seawater into drinking water at scale, already vital in the Gulf and Israel."],
    ["Ageing Societies", "Japan, Italy and Germany already have more people over 65 than under 15."],
  ],

  'Strange but True': [
    ["The Emu War", "In 1932 Australia’s army fought emus with machine guns, and largely lost."],
    ["The Great Molasses Flood", "In 1919 a wave of molasses swept through Boston, killing 21 people."],
    ["The Tanganyika Laughter Epidemic", "In 1962 contagious laughter spread through schools in Tanzania, closing some."],
    ["Mike the Headless Chicken", "A chicken in Colorado lived for about 18 months after most of its head was cut off."],
    ["The Baghdad Battery", "Ancient clay jars that some claim were batteries, though most archaeologists doubt it."],
    ["The Wow! Signal", "A strong radio signal detected in 1977 that has never been found again."],
    ["Lake Nyos", "In 1986 a Cameroon lake released a cloud of carbon dioxide that killed over 1,700 people."],
    ["The Dyatlov Pass Incident", "Nine Soviet hikers died mysteriously in 1959; an avalanche is the leading explanation."],
    ["The Mary Celeste", "A ship found drifting in 1872 with its crew gone and its cargo mostly intact."],
    ["Ball Lightning", "Glowing orbs during storms have been reported for centuries and are still not fully explained."],
    ["Turritopsis dohrnii", "The so-called immortal jellyfish can revert to a younger stage of life."],
    ["Zombie Ants", "A fungus takes over ants’ bodies and makes them climb before it sprouts from their heads."],
    ["Mpemba Effect", "Under some conditions hot water seems to freeze faster than cold, and scientists still argue about it."],
    ["Spontaneous Human Combustion", "Rare cases where bodies burned almost completely; the ‘wick effect’ offers an explanation."],
    ["The Pitch Drop Experiment", "Since 1927, pitch has dripped through a funnel in Australia, about once a decade."],
    ["The Oklo Natural Reactor", "Two billion years ago, a uranium deposit in Gabon ran as a natural nuclear reactor."],
    ["Singing Sand Dunes", "Some dunes boom or hum loudly when sand slides down them."],
    ["Blood Falls", "In Antarctica, iron-rich water stains a glacier blood-red."],
    ["Raining Animals", "Fish and frogs have reportedly fallen from the sky, probably lifted by waterspouts."],
    ["The Taos Hum", "Some residents of Taos, New Mexico, report a low hum that others can’t hear."],
    ["Déjà Vu", "The eerie sense that a new moment has happened before."],
    ["Cotard’s Syndrome", "A rare condition in which people believe they are dead."],
    ["Foreign Accent Syndrome", "After brain injury some people suddenly speak with what sounds like a foreign accent."],
    ["The McGurk Effect", "Seeing lips say ‘ga’ while hearing ‘ba’ can make you hear ‘da’."],
    ["Mirages", "Hot air bends light, making the sky appear like water on a road."],
    ["Fata Morgana", "Complex mirages can make ships appear to float above the horizon."],
    ["Bioluminescent Bays", "In Puerto Rico, plankton make water glow blue when it is disturbed."],
    ["Operation Mincemeat", "In 1943 the British fooled the Nazis with a corpse carrying fake invasion plans."],
    ["The Cottingley Fairies", "Two girls’ fairy photos fooled many, including Arthur Conan Doyle."],
    ["The Great Stink", "In 1858 the Thames smelled so bad that it pushed Parliament to fund London’s sewers."],
    ["Defenestrations of Prague", "Throwing officials out of windows happened more than once in Prague’s history."],
    ["The Cadaver Synod", "In 897 a pope put his predecessor’s exhumed corpse on trial."],
    ["Lost Cities Found by Laser", "LiDAR has revealed vast Maya settlements hidden under the jungle."],
    ["The Kola Superdeep Borehole", "The Soviet Union drilled over 12 km down, about a third of the way through the crust there."],
    ["Coelacanths", "A fish thought extinct for 66 million years turned up alive in 1938."],
    ["Pigeon-Guided Missiles", "B.F. Skinner trained pigeons to steer bombs during WWII."],
    ["Project Habakkuk", "Britain considered building aircraft carriers out of ice mixed with wood pulp."],
    ["The Bloop", "A loud underwater sound recorded in 1997, later attributed to icequakes."],
    ["Stone Spheres of Costa Rica", "Hundreds of near-perfect stone balls carved by an ancient culture."],
    ["The Toynbee Tiles", "Mysterious tiles embedded in city streets, with cryptic messages about Jupiter."],
    ["Moving Rocks of Death Valley", "Rocks slide across a dry lakebed, pushed by thin ice and wind."],
    ["The Placebo Surgery", "In some trials, fake knee surgery helped about as much as real surgery."],
    ["The Hessdalen Lights", "Unexplained glowing lights have been seen in a Norwegian valley for decades."],
    ["Animal Trials", "Medieval European courts put pigs, rats and insects on trial."],
    ["Lake Natron", "A Tanzanian lake so alkaline that dead birds can end up looking like stone statues."],
    ["The Crooked Forest", "In Poland, about 400 pine trees grow with a sharp bend at the base, and no one knows why."],
    ["Eternal Flame Falls", "In New York State, a small flame burns in a grotto behind a waterfall, fed by natural gas."],
    ["The Winchester House", "A mansion in California with doors that open onto walls and stairs that lead to the ceiling."],
    ["The Flannan Isles Mystery", "In 1900 three lighthouse keepers vanished from a remote Scottish island."],
    ["Fairy Circles", "Bare round patches dot Namibian grasslands, and scientists still argue over what makes them."],
    ["The Bermuda Triangle", "Famous for disappearances, but studies find it no more dangerous than other busy waters."],
  ],

  'Games & Play': [
    ["Homo Ludens", "Johan Huizinga argued that play is older than culture and helped shape it."],
    ["Chess", "The number of possible chess games is far larger than the number of atoms in the observable universe."],
    ["Go", "AlphaGo’s ‘move 37’ in 2016 surprised professional players with its creativity."],
    ["Mancala", "One of the oldest families of board games, played with seeds or stones in pits."],
    ["The Royal Game of Ur", "A 4,500-year-old Mesopotamian board game whose rules were reconstructed from a cuneiform tablet."],
    ["Senet", "Ancient Egyptians played this board game, later linked to the soul’s journey."],
    ["Playing Cards", "Cards probably came from China and arrived in Europe in the 1300s."],
    ["Tarot as a Game", "Tarot cards were first used to play a trick-taking game in Italy."],
    ["Tabletop Role-Playing", "Dungeons & Dragons (1974) turned storytelling into a shared game."],
    ["Improv Theatre", "‘Yes, and…’: accept what your partner offers and build on it."],
    ["Monopoly’s Origin", "It descends from The Landlord’s Game, designed by Lizzie Magie to criticise landlords."],
    ["Video Game Design", "Nintendo’s level 1-1 in Super Mario Bros. teaches the player without words."],
    ["Tetris", "Designed by Alexey Pajitnov in the Soviet Union, it has been played by millions."],
    ["The Tetris Effect", "After playing a lot, people see falling blocks when they close their eyes."],
    ["Speedrunning", "Players race to finish games as fast as possible, sometimes by glitching through walls."],
    ["Puzzle Hunts", "Teams solve chains of puzzles where even the instructions are hidden."],
    ["Escape Rooms", "Locked in a room with clues, groups must solve their way out in an hour."],
    ["Crosswords", "The first crossword appeared in a New York newspaper in 1913."],
    ["Cryptic Crosswords", "British crosswords hide each answer inside wordplay and a definition."],
    ["Sudoku", "Its modern form was invented in the US and named and popularised in Japan."],
    ["Rubik’s Cube", "The cube has over 43 quintillion positions, yet can be solved in 20 moves or fewer."],
    ["Juggling", "Mathematicians write juggling patterns as numbers, called siteswap notation."],
    ["Kites", "Kites flew in China over two thousand years ago, sometimes for military signals."],
    ["Hide and Seek", "Versions are played by children all over the world."],
    ["Rock Paper Scissors", "There are world championships, and good players exploit predictable human patterns."],
    ["Play in Animals", "Rats laugh when tickled, and young ravens slide down snowy roofs for fun."],
    ["Children’s Street Games", "Hopscotch and clapping games pass from child to child for generations."],
    ["Olympic Origins", "The ancient Olympics began in 776 BC according to tradition, and athletes competed naked."],
    ["The Mesoamerican Ballgame", "Players struck a heavy rubber ball with their hips; some games may have ended in sacrifice."],
    ["Buzkashi", "Afghan horsemen compete to carry a goat carcass to the goal."],
    ["Sepak Takraw", "A Southeast Asian sport like volleyball, played with feet and a rattan ball."],
    ["Parkour", "Moving through a city by running, jumping and climbing over obstacles."],
    ["Skateboarding", "Born in empty California swimming pools during a 1970s drought."],
    ["Game Theory in Games", "Poker players bluff, and the mathematics shows that sometimes they should."],
    ["Poker", "A game of incomplete information where you play the person, not just the cards."],
    ["Magic Tricks", "Magicians exploit attention, memory and expectation to fool the brain."],
    ["Riddles", "The Sphinx asked what walks on four legs in the morning, two at noon and three in the evening."],
    ["Lateral Thinking Puzzles", "Edward de Bono coined ‘lateral thinking’ for solving problems from unexpected angles."],
    ["Oulipo’s Games", "French writers set themselves constraints, like writing a whole novel without the letter e."],
    ["Exquisite Corpse", "Surrealists took turns drawing or writing without seeing what came before."],
    ["Lego", "The name comes from the Danish ‘leg godt’, meaning ‘play well’."],
    ["Minecraft", "A game of blocks where players have built working computers inside the game."],
    ["Gamification", "Points and badges can motivate, but they can also crowd out the joy of doing something for itself."],
    ["Infinite Games", "James Carse: finite games are played to win; infinite games are played to keep playing."],
    ["The Magic Circle", "When you play, you step into a space with its own rules."],
    ["Toys Through History", "Ancient children played with dolls, spinning tops and small carts."],
    ["Dominoes", "Domino toppling shows can involve hundreds of thousands of pieces."],
    ["Charades", "A parlour game that became a way to practise communicating without words."],
    ["Backgammon", "One of the oldest board games still played, with roots in ancient Persia."],
    ["Mahjong", "A Chinese tile game from the 19th century, now played around the world."],
  ],
}
