// The Lab's hand-written topic library. No network, no AI — just curiosity, curated.
import { MORE_TOPICS } from './topics-more'

export const CATEGORIES = [
  'Art',
  'Music',
  'Philosophy',
  'Psychology',
  'Science',
  'History',
  'Culture & Anthropology',
  'Literature',
  'Mathematics',
  'Economics & Game Theory',
  'Architecture & Design',
  'Religion & Myth',
  'Technology',
  'Nature & Biology',
  'Language',
] as const

export type Category = (typeof CATEGORIES)[number]

export interface Topic {
  name: string
  category: Category
  hook: string
}

export const CATEGORY_COLORS: Record<Category, string> = {
  // Mid-tone, Apple system-style hues that read on both white and black.
  Art: '#ff2d55',
  Music: '#ff9500',
  Philosophy: '#af52de',
  Psychology: '#5ac8fa',
  Science: '#007aff',
  History: '#a2845e',
  'Culture & Anthropology': '#ff6f61',
  Literature: '#5e5ce6',
  Mathematics: '#00c7be',
  'Economics & Game Theory': '#34c759',
  'Architecture & Design': '#8e8e93',
  'Religion & Myth': '#d4a500',
  Technology: '#30b0c7',
  'Nature & Biology': '#7fb800',
  Language: '#c44db1',
}

export const CATEGORY_GLYPHS: Record<Category, string> = {
  Art: '✦',
  Music: '♪',
  Philosophy: '∴',
  Psychology: '◎',
  Science: '⚛',
  History: '⌛',
  'Culture & Anthropology': '◈',
  Literature: '❡',
  Mathematics: '∑',
  'Economics & Game Theory': '⚖',
  'Architecture & Design': '△',
  'Religion & Myth': '☽',
  Technology: '⌁',
  'Nature & Biology': '❦',
  Language: '“',
}

type Raw = [name: string, hook: string]

const RAW: Record<Category, Raw[]> = {
  Art: [
    ['Kintsugi', 'Japanese menders repair broken pottery with gold-dusted lacquer, so the crack becomes the most beautiful part of the bowl.'],
    ['Chiaroscuro', 'Caravaggio pulled figures out of pitch darkness with a single raking light, and painting never looked at shadows the same way again.'],
    ['Trompe-l’œil', 'Painters have fooled birds, popes and visitors into reaching for objects that are nothing but pigment on a flat wall.'],
    ['Dada', 'Born in a Zurich cabaret during World War I, Dada answered a senseless war with deliberate nonsense.'],
    ['Duchamp’s Fountain', 'In 1917 a signed, store-bought urinal asked the question art has never stopped arguing about: who decides what art is?'],
    ['Ukiyo-e', 'The ‘pictures of the floating world’ were cheap woodblock prints that ended up rewiring the eyes of Van Gogh and Monet.'],
    ['Lascaux Cave Paintings', 'Around 17,000 years ago someone crawled deep underground by lamplight to paint aurochs that still seem to move.'],
    ['Vantablack', 'A coating of carbon nanotubes so absorbent that a crumpled sheet of foil painted with it looks like a flat hole in space.'],
    ['Pointillism', 'Seurat painted with dots of pure colour and let your eye do the mixing, turning optics into an art movement.'],
    ['Suprematism', 'Malevich’s Black Square (1915) aimed to be the zero point of painting: nothing left but feeling and form.'],
    ['Land Art', 'Robert Smithson’s Spiral Jetty is a 450-metre coil of basalt in the Great Salt Lake that vanishes and reappears with the water level.'],
    ['The Ghent Altarpiece', 'Possibly the most stolen artwork in history, one of its panels has been missing since 1934 and may never be found.'],
    ['Memento Mori', 'Skulls, guttering candles and wilting flowers tucked into still lifes whispered one message: remember you will die.'],
    ['Anamorphosis', 'Holbein hid a distorted skull in The Ambassadors that snaps into focus only when you view the painting from the side.'],
    ['Fluxus', 'Fluxus artists wrote ‘event scores’ like instructions for a piece of music, except the piece might be ‘draw a straight line and follow it’.'],
    ['Sfumato', 'Leonardo blended tones ‘like smoke’ so finely that X-rays of the Mona Lisa show dozens of glazes thinner than a hair.'],
    ['Persian Miniatures', 'Painted with brushes traditionally said to use a few hairs from a kitten or squirrel, these jewel-like illustrations deliberately reject single-point perspective.'],
    ['Wabi-sabi', 'An aesthetic that finds beauty in things that are imperfect, impermanent and incomplete: moss on stone, a lopsided tea bowl.'],
    ['Outsider Art', 'Henry Darger, a hospital janitor, left behind a 15,000-page illustrated epic that no one saw until after he died.'],
    ['The Rothko Chapel', 'Fourteen nearly black canvases in a Houston octagon have reduced visitors to tears without depicting anything at all.'],
    ['Aboriginal Dot Painting', 'The Papunya Tula movement of the 1970s moved ancient sand and body designs onto canvas, encoding sacred country in dots.'],
    ['Art Forgery of Han van Meegeren', 'A Dutch painter sold fake Vermeers to the Nazis, then had to forge one in court to prove he wasn’t a collaborator.'],
    ['Impasto', 'Van Gogh laid paint on so thickly that his skies are sculptures, and their ridges catch real light.'],
    ['The Bayeux Tapestry', 'Actually an embroidery, this roughly 70-metre stitched chronicle of 1066 even shows Halley’s Comet blazing overhead as an omen.'],
    ['Futurism', 'Italian Futurists worshipped speed and machines and wanted to burn down museums, then many of them embraced fascism.'],
    ['Banksy and Street Art', 'In 2018 a Banksy painting shredded itself moments after selling at Sotheby’s, and became worth more for it.'],
    ['Russian Icon Painting', 'Icons use reverse perspective, lines that widen as they recede, so the image seems to open toward the viewer.'],
    ['Tenebrism', 'An extreme form of chiaroscuro where most of the canvas is swallowed by darkness and figures erupt into spotlight.'],
  ],
  Music: [
    ['Gamelan Music', 'Balinese and Javanese gamelan orchestras tune each ensemble as a unique set, so instruments cannot be swapped between groups.'],
    ['The Tritone', 'Nicknamed ‘diabolus in musica’, the augmented fourth has unsettled listeners for centuries and drives every jazz dominant chord.'],
    ['John Cage’s 4′33″', 'A pianist sits silently for four and a half minutes, and the music is whatever the audience happens to hear.'],
    ['Throat Singing', 'Tuvan khoomei singers produce two or more pitches at once by shaping overtones in their mouths.'],
    ['The Blue Note', 'Blues singers bend notes into the cracks between piano keys, pitches Western notation was never built to hold.'],
    ['Gregorian Chant', 'Medieval monks invented the musical staff partly to stop having to memorise thousands of chants by ear.'],
    ['Musique Concrète', 'Pierre Schaeffer made music in 1948 from recorded train noises, inventing sampling decades before hip-hop.'],
    ['The Amen Break', 'Six seconds of drumming from a 1969 B-side became one of the most sampled loops ever and the backbone of jungle music.'],
    ['Raga', 'In Hindustani music, many ragas are tied to specific times of day or seasons, and playing one at the wrong hour is a faux pas.'],
    ['Minimalism (Music)', 'Steve Reich’s phase pieces let two identical loops drift apart, creating patterns no one actually plays.'],
    ['The Theremin', 'The first electronic instrument you play without touching: your hands warp two radio fields to control pitch and volume.'],
    ['Polyrhythm', 'West African drumming layers 3 against 2 against 4 until the beat seems to live in the space between players.'],
    ['Equal Temperament', 'Every piano is very slightly out of tune on purpose, a compromise that lets music modulate into any key.'],
    ['The Mozart Effect', 'A 1993 study about students and spatial reasoning snowballed into a myth that classical music makes babies smarter.'],
    ['Fado', 'Portuguese fado is built around saudade, a longing for something that may never return, or may never have existed.'],
    ['Auto-Tune', 'Built from seismic-survey maths for oil exploration, it was meant to be invisible until Cher made it the sound itself.'],
    ['Earworms', 'Involuntary musical imagery tends to be simple, repetitive and slightly surprising, and chewing gum may help get rid of it.'],
    ['The Devil’s Trill Sonata', 'Tartini claimed he heard the Devil play a violin sonata in a dream and spent his life failing to transcribe it.'],
    ['Microtonal Music', 'Harry Partch built his own instruments to play a 43-tone scale and named one of them the Chromelodeon.'],
    ['Sea Shanties', 'Shanties were work tools: their call-and-response rhythms synchronised sailors hauling ropes together.'],
    ['The Wolf Tone', 'Cellos and violins can have a note that stutters and howls because the body resonates against the string.'],
    ['Flamenco Duende', 'Lorca described duende as a dark, earthy spirit that rises through a performer’s feet when art brushes against death.'],
    ['Synesthesia in Composers', 'Scriabin designed a ‘colour organ’ to project light during his symphony Prometheus because he saw keys as colours.'],
    ['Overtone Series', 'Every note you hear is secretly a chord of higher frequencies, and their recipe is what makes a flute sound unlike an oboe.'],
    ['The Loudness War', 'From the 1990s, albums were mastered ever louder and more compressed until music literally lost its dynamics.'],
    ['Bebop', 'Charlie Parker and Dizzy Gillespie turned jazz from dance music into breakneck art for listening, in late-night jam sessions.'],
    ['Kecak', 'The Balinese ‘monkey chant’ is performed by a circle of up to a hundred men chanting interlocking ‘cak’ rhythms.'],
    ['Shepard Tone', 'An auditory illusion of a pitch that rises forever without ever getting higher, used to build endless tension in film scores.'],
  ],
  Philosophy: [
    ['The Ship of Theseus', 'If you replace every plank of a ship one by one, is it still the same ship, and what if someone rebuilds the old planks?'],
    ['Simulacra and Simulation', 'Baudrillard argued we live among copies with no original, signs that point only to other signs.'],
    ['Plato’s Cave', 'Prisoners watching shadows on a wall mistake them for reality, and the freed one who returns is mocked.'],
    ['Zeno’s Paradoxes', 'To cross a room you must first cross half of it, then half the rest, forever, so how does anything move at all?'],
    ['The Trolley Problem', 'Would you pull a lever to kill one person and save five? Most say yes, until the lever becomes a push.'],
    ['Absurdism', 'Camus said we must imagine Sisyphus happy, pushing his boulder forever in a universe that offers no meaning.'],
    ['The Experience Machine', 'Robert Nozick asked whether you would plug into a machine that guarantees perfect pleasure for life. Most people refuse.'],
    ['Stoicism', 'Epictetus, a former slave, taught that we are disturbed not by things but by our judgments about things.'],
    ['Mary’s Room', 'A colour scientist who knows every physical fact about red, but has never seen it, steps outside. Does she learn something new?'],
    ['Sorites Paradox', 'One grain of sand is not a heap, and adding one grain never makes a heap, so heaps cannot exist.'],
    ['Wittgenstein’s Beetle in a Box', 'If everyone has a box with a ‘beetle’ no one else can see, the word ‘beetle’ cannot refer to what is inside.'],
    ['Pascal’s Wager', 'Bet on God, Pascal argued: if you lose you lose little, if you win you win infinitely. Critics ask which god.'],
    ['The Veil of Ignorance', 'Rawls asked: what society would you design if you did not know whether you would be born rich, poor or sick?'],
    ['Philosophical Zombies', 'Could there be a being physically identical to you, behaving just like you, with no inner experience at all?'],
    ['Eternal Recurrence', 'Nietzsche’s test: would you live this exact life again, every moment, infinitely? Could you say yes?'],
    ['Occam’s Razor', 'Don’t multiply entities beyond necessity, a principle William of Ockham probably never phrased that way.'],
    ['Ubuntu Philosophy', 'A southern African ethic summed up as ‘I am because we are’: personhood comes through other people.'],
    ['Zhuangzi’s Butterfly Dream', 'Zhuangzi dreamed he was a butterfly, then woke and wondered if he was a butterfly dreaming he was Zhuangzi.'],
    ['The Problem of Induction', 'Hume noticed that no number of sunrises logically proves the sun will rise tomorrow.'],
    ['Existentialism', 'Sartre claimed existence precedes essence: you are thrown into the world first, and must invent who you are.'],
    ['Buridan’s Ass', 'A donkey placed exactly between two identical bales of hay starves, because it has no reason to choose either.'],
    ['Gettier Problems', 'A three-page 1963 paper showed you can have a justified true belief and still not know something.'],
    ['Panpsychism', 'Maybe consciousness is not rare but fundamental, and even electrons have some tiny flicker of experience.'],
    ['The Chinese Room', 'Searle imagined a man following rules to answer Chinese messages perfectly without understanding a word.'],
    ['Epicureanism', 'Epicurus was no glutton: his ‘pleasure’ meant the absence of pain and fear, plus good friends and simple bread.'],
    ['Hegelian Dialectic', 'Thesis meets antithesis and births a synthesis, though Hegel himself rarely used those exact words.'],
    ['Moral Luck', 'Two equally drunk drivers: one hits a child, one doesn’t. We blame them differently for what was pure chance.'],
    ['Brain in a Vat', 'How do you know you are not a brain in a vat being fed perfect signals? Putnam argued the sentence refutes itself.'],
  ],
  Psychology: [
    ['Dunbar’s Number', 'Robin Dunbar linked primate brain size to group size and proposed humans can maintain about 150 stable relationships.'],
    ['The Stanford Prison Experiment', 'The infamous 1971 study is now heavily criticised: guards may have been coached into cruelty.'],
    ['Cognitive Dissonance', 'Festinger infiltrated a doomsday cult and watched believers grow more devout when the world failed to end.'],
    ['The Dunning-Kruger Effect', 'People with low skill in a domain tend to overestimate it, partly because the skill to judge is the skill itself.'],
    ['Flow State', 'Csikszentmihalyi found people are happiest fully absorbed in a task at the edge of their ability, losing track of time.'],
    ['The Baader-Meinhof Phenomenon', 'Learn a new word and suddenly it is everywhere: frequency illusion is your attention, not the universe.'],
    ['Learned Helplessness', 'Organisms that learn their actions don’t matter can stop trying even when escape becomes possible.'],
    ['The Marshmallow Test', 'Delayed gratification in four-year-olds seemed to predict life outcomes, but replications point to family background.'],
    ['Change Blindness', 'In experiments, people giving directions often fail to notice when the stranger they are talking to is swapped for another.'],
    ['The Zeigarnik Effect', 'Unfinished tasks nag at memory more than finished ones, which is why cliffhangers work.'],
    ['Attachment Theory', 'Bowlby and Ainsworth found infants’ early bonds form templates that echo through adult love.'],
    ['Pareidolia', 'Seeing faces in clouds, sockets and burnt toast is your brain’s face-detector firing with hair-trigger sensitivity.'],
    ['The Milgram Experiment', 'Around two-thirds of participants kept administering what they thought were dangerous shocks when told to continue.'],
    ['The Spotlight Effect', 'People wearing an embarrassing T-shirt guessed half the room noticed; only about a quarter actually did.'],
    ['Hedonic Treadmill', 'Lottery winners and people with new injuries both drift back toward their baseline happiness surprisingly quickly.'],
    ['Confabulation', 'Split-brain patients invent fluent, confident explanations for actions their other hemisphere actually chose.'],
    ['The Bystander Effect', 'The more witnesses there are, the less likely any one of them is to help, as responsibility diffuses.'],
    ['Impostor Phenomenon', 'High achievers often feel like frauds about to be exposed, despite every external sign of competence.'],
    ['Peak-End Rule', 'We judge experiences mostly by their most intense moment and their ending, not their total length.'],
    ['Mirror Self-Recognition', 'Only a few species, including great apes, dolphins and magpies, seem to recognise themselves in a mirror.'],
    ['Choice Overload', 'In a famous jam study, shoppers offered 24 flavours bought less often than those offered 6.'],
    ['Jungian Archetypes', 'Jung believed the Shadow, the Trickster and the Wise Old Man recur in dreams and myths across every culture.'],
    ['The IKEA Effect', 'We value things more when we built them ourselves, even badly.'],
    ['Synesthesia', 'For some people the number 7 is always yellow, or the word ‘Tuesday’ tastes faintly of lemon.'],
    ['False Memory', 'Elizabeth Loftus showed that a few suggestive questions can implant vivid memories of events that never happened.'],
    ['The Rubber Hand Illusion', 'Stroke a fake hand in sync with your hidden real one and your brain starts to feel the rubber as yours.'],
    ['Default Mode Network', 'A set of brain regions lights up when you are doing nothing in particular, daydreaming, remembering and imagining.'],
    ['Terror Management Theory', 'Reminders of death make people cling harder to their worldviews, a finding from hundreds of experiments.'],
  ],
  Science: [
    ['Quantum Entanglement', 'Measure one particle and its partner’s result is instantly correlated, even light-years away, without sending any signal.'],
    ['The Fermi Paradox', 'The galaxy is old and vast, so where is everybody?'],
    ['Schrödinger’s Cat', 'Schrödinger invented his half-dead cat to mock quantum superposition, and it became its mascot instead.'],
    ['Entropy', 'The universe’s disorder always increases, which may be the only reason time seems to flow in one direction.'],
    ['Dark Matter', 'Galaxies spin too fast for their visible mass, so roughly 85% of all matter seems to be something we cannot see.'],
    ['The Double-Slit Experiment', 'Fire single electrons at two slits and they build an interference pattern, as if each went through both.'],
    ['Black Hole Information Paradox', 'If black holes evaporate, does the information that fell in vanish, breaking a basic rule of physics?'],
    ['Plate Tectonics', 'Alfred Wegener’s continental drift was ridiculed for decades until seafloor maps revealed spreading ridges.'],
    ['The Cosmic Microwave Background', 'Two radio engineers first blamed pigeon droppings for the faint hiss that turned out to be the Big Bang’s afterglow.'],
    ['Chaos Theory', 'Edward Lorenz rounded one number in a weather model and got an utterly different forecast.'],
    ['Superconductivity', 'Cool certain materials enough and electrical resistance drops to exactly zero, letting magnets float.'],
    ['The Higgs Field', 'Particles get their mass by wading through an invisible field filling all of space, confirmed in 2012.'],
    ['Panspermia', 'Could life have hitchhiked to Earth on meteorites? Martian rocks have definitely landed here.'],
    ['Neutrinos', 'Trillions of these ghostly particles pass through your body every second, almost never touching anything.'],
    ['Tardigrades', 'Water bears survive boiling, near-absolute zero, crushing pressure and even the vacuum of space.'],
    ['The Great Oxygenation Event', 'About 2.4 billion years ago, cyanobacteria poisoned the planet with oxygen and set the stage for us.'],
    ['Time Dilation', 'GPS satellites must correct for relativity every day, or your map would drift by kilometres.'],
    ['Antimatter', 'Every particle has a mirror twin with opposite charge, yet the universe is made almost entirely of matter. Why?'],
    ['Prions', 'Misfolded proteins that can make other proteins misfold, causing diseases with no DNA or RNA involved.'],
    ['Maxwell’s Demon', 'A tiny being sorting fast and slow molecules seemed to beat the second law, until information itself had a cost.'],
    ['Snowball Earth', 'Hundreds of millions of years ago the planet may have frozen nearly pole to pole, more than once.'],
    ['The Butterfly Effect', 'Tiny changes in initial conditions can swing the outcome of chaotic systems completely, in principle and practice.'],
    ['Gravitational Waves', 'In 2015 LIGO detected a ripple in spacetime smaller than a proton’s width, from two black holes colliding.'],
    ['The Placebo Effect', 'Even placebos openly labelled as fake pills have helped some patients in trials.'],
    ['Radiocarbon Dating', 'Nuclear bomb tests doubled atmospheric carbon-14, letting scientists date cells in your body to the year.'],
    ['Exoplanets', 'The first planets found around another star orbited a pulsar, a dead star blasting radiation.'],
    ['Emergence', 'Wetness isn’t in any single water molecule, and minds may not be in any single neuron.'],
    ['Quantum Tunnelling', 'Particles can pass through barriers they don’t have the energy to climb, which is why the Sun can shine.'],
  ],
  History: [
    ['Byzantine Iconoclasm', 'For over a century Byzantine emperors smashed religious images, sparking riots and a struggle over what can be depicted.'],
    ['The Library of Alexandria', 'It probably didn’t burn in one dramatic fire but declined slowly through budget cuts and neglect.'],
    ['The Tulip Mania', 'In 1630s Holland, a single tulip bulb reportedly traded for the price of a canal house, though the crash is often exaggerated.'],
    ['The Dancing Plague of 1518', 'In Strasbourg, dozens of people danced uncontrollably for days, and authorities hired musicians to help.'],
    ['The Bronze Age Collapse', 'Around 1177 BCE, the great civilisations of the Mediterranean fell almost at once, and we still argue about why.'],
    ['The Silk Road', 'More a web than a road, it carried silk, paper, gunpowder, religions and, eventually, the Black Death.'],
    ['The Carrington Event', 'An 1859 solar storm set telegraph wires sparking and lit up auroras as far south as the Caribbean.'],
    ['Mansa Musa', 'The Mali emperor’s 1324 pilgrimage gave away so much gold in Cairo that he depressed its value for years.'],
    ['The Christmas Truce', 'In 1914, soldiers on the Western Front climbed out of the trenches to sing, swap gifts and play football.'],
    ['The Antikythera Mechanism', 'A 2,000-year-old Greek bronze device of gears that predicted eclipses, an analogue computer lost at sea.'],
    ['The Great Emu War', 'In 1932, Australia sent soldiers with machine guns against emus, and the emus won.'],
    ['The Radium Girls', 'Factory workers painted watch dials with glowing radium and were told to lick their brushes to a point.'],
    ['The Cuban Missile Crisis', 'Soviet officer Vasili Arkhipov may have prevented nuclear war by refusing to approve a torpedo launch.'],
    ['The Year Without a Summer', 'The 1815 Tambora eruption caused snow in June, famine, and the gloomy holiday that produced Frankenstein.'],
    ['The Mongol Postal System', 'The Yam relay network of horses and stations let messages cross the Mongol Empire at astonishing speed.'],
    ['The Defenestrations of Prague', 'Prague has a habit of throwing officials out of windows, and one such incident helped start the Thirty Years’ War.'],
    ['The Rosetta Stone', 'One decree written in hieroglyphs, Demotic and Greek finally let Champollion crack Egyptian writing.'],
    ['The Haitian Revolution', 'The only successful slave revolt to found a nation, it terrified empires and reshaped the Louisiana Purchase.'],
    ['Göbekli Tepe', 'Massive carved pillars built around 9500 BCE, before farming, writing or the wheel, upended theories of civilisation.'],
    ['The Taiping Rebellion', 'A man who believed he was Jesus’s younger brother led a civil war that killed perhaps 20 million people.'],
    ['The Hanseatic League', 'A medieval network of merchant towns ran its own trade empire across northern Europe for centuries.'],
    ['The Lost Colony of Roanoke', 'An entire English settlement vanished, leaving only the word ‘CROATOAN’ carved into a post.'],
    ['The Phoenicians and Purple Dye', 'Tyrian purple took thousands of crushed sea snails per gram, so the colour became the badge of emperors.'],
    ['The Children’s Crusade', 'Legend says thousands of children marched to free Jerusalem in 1212; the reality was poor youths and wanderers.'],
    ['Sumerian Beer', 'One of the oldest written recipes is a hymn to Ninkasi, goddess of beer, from ancient Mesopotamia.'],
    ['The Khmer Empire’s Angkor', 'Angkor may have been the largest pre-industrial city on Earth, sustained by a vast water-management network.'],
    ['The Venetian Arsenal', 'Venice’s shipyard could assemble a war galley in a day using standardised parts, centuries before Ford.'],
    ['The Sea Peoples', 'Mysterious raiders appear in Egyptian records around the Bronze Age collapse, and no one knows exactly who they were.'],
  ],
  'Culture & Anthropology': [
    ['Potlatch', 'Pacific Northwest peoples held feasts where status came from how much you gave away, or even destroyed.'],
    ['The Kula Ring', 'Trobriand islanders circulate shell necklaces and armbands in opposite directions around an island chain, forever.'],
    ['Hygge', 'The Danish art of cosiness: candles, wool socks and the warm feeling of being safely together.'],
    ['Cargo Cults', 'After WWII, some Melanesian communities built bamboo airstrips hoping to summon the planes that brought goods.'],
    ['Day of the Dead', 'In Mexico, families build ofrendas of marigolds, sugar skulls and favourite foods to welcome the dead home.'],
    ['Tea Ceremony (Chanoyu)', 'The Japanese way of tea turns making a single bowl into a choreography of respect, purity and tranquillity.'],
    ['Rai Stones of Yap', 'Giant stone discs served as money on Yap, and ownership changed hands without the stones ever moving.'],
    ['The Hikikomori', 'In Japan, over a million people are estimated to withdraw almost completely from social life for months or years.'],
    ['Famadihana', 'In Madagascar, families exhume ancestors, rewrap them in fresh silk shrouds and dance with them.'],
    ['Ikigai', 'Often drawn as a four-circle Venn diagram, Okinawan ikigai is really about small daily reasons to get up.'],
    ['The Gift (Marcel Mauss)', 'Mauss argued no gift is truly free: every gift creates an obligation to receive and to give back.'],
    ['Lagom', 'A Swedish word for ‘just the right amount’, neither too much nor too little.'],
    ['Sky Burial', 'In Tibet, bodies may be offered to vultures as a final act of generosity to living beings.'],
    ['The Hadza', 'Tanzanian hunter-gatherers whose sleep, diet and gut microbes have taught researchers about our deep past.'],
    ['Carnival', 'Before Lent, the world turns upside down: peasants become kings, masks hide everyone, and rules dissolve.'],
    ['Polynesian Wayfinding', 'Navigators crossed thousands of kilometres of open Pacific by reading stars, swells and birds.'],
    ['Liminality', 'Rites of passage have an in-between phase where you are neither who you were nor who you will be.'],
    ['Saudade', 'A Portuguese and Galician longing for something absent, flavoured with the love that remains.'],
    ['Haka', 'The Māori haka is not only a war dance; it is performed at funerals, weddings and to honour guests.'],
    ['Tattoos of Ötzi the Iceman', 'The 5,300-year-old Iceman had 61 tattoos, many over joints, possibly as a form of therapy.'],
    ['The Dowry and Bride Price', 'Opposite flows of wealth at marriage reveal how different societies value labour, land and lineage.'],
    ['Cosplay', 'Fans who sew armour and wigs for months to become a character are part of a global folk-art movement.'],
    ['Thick Description', 'Clifford Geertz showed that a wink and a twitch look the same; only culture tells you which is which.'],
    ['The Sapeurs of Congo', 'In Brazzaville and Kinshasa, La Sape turns impeccable designer suits into a philosophy of joy and dignity.'],
    ['Omertà', 'A southern Italian code of silence that made the Mafia almost impossible to prosecute for generations.'],
    ['Wife Carrying Championships', 'Finland’s eiukonkanto race traditionally awards the winner his partner’s weight in beer.'],
    ['Joking Relationships', 'Some West African clans are obliged to tease each other mercilessly, a ritual insult that keeps peace.'],
    ['Silent Trade', 'Historically, some traders left goods on a beach and retreated, letting partners they never met leave payment.'],
  ],
  Literature: [
    ['The Voynich Manuscript', 'A 15th-century book written in an unknown script, full of strange plants and bathing women, that no one can read.'],
    ['Borges’ Library of Babel', 'A library containing every possible 410-page book, which means it holds every truth and every lie.'],
    ['Magical Realism', 'García Márquez wrote of a woman ascending to heaven while folding laundry, as plainly as reporting the weather.'],
    ['The Unreliable Narrator', 'Some narrators lie to you, some lie to themselves, and the best novels make you complicit.'],
    ['Oulipo', 'Georges Perec wrote a whole novel, La Disparition, without ever using the letter ‘e’.'],
    ['The Epic of Gilgamesh', 'Humanity’s oldest great story is about a king who loses his best friend and goes searching for immortality.'],
    ['Stream of Consciousness', 'Joyce’s Ulysses ends with a 4,000-word passage of Molly Bloom’s thoughts with almost no punctuation.'],
    ['Kafkaesque', 'Kafka asked his friend to burn all his manuscripts; Max Brod published them instead.'],
    ['The Hero’s Journey', 'Joseph Campbell’s monomyth claims a single story shape underlies myths worldwide, and Star Wars borrowed it openly.'],
    ['Tristram Shandy', 'An 18th-century novel with a black page, a marbled page and a narrator who doesn’t get born until volume three.'],
    ['Haiku', 'Bashō’s frog jumping into an old pond became perhaps the most translated poem in history.'],
    ['The Death of the Author', 'Barthes argued a text’s meaning is born in the reader, not the writer’s intentions.'],
    ['One Thousand and One Nights', 'Scheherazade survives by never finishing a story, nesting tales within tales until the king relents.'],
    ['Chekhov’s Gun', 'If a gun hangs on the wall in Act One, it must go off by Act Three.'],
    ['Afrofuturism', 'From Sun Ra to Octavia Butler, Afrofuturism imagines Black futures with technology, myth and cosmic scale.'],
    ['The Tale of Genji', 'Written by a Japanese court lady around 1000 CE, it is often called the world’s first novel.'],
    ['Ekphrasis', 'Poems that describe artworks, like Keats’s Ode on a Grecian Urn, let one art speak through another.'],
    ['The Picture of Dorian Gray', 'A portrait ages and decays with a man’s sins while he stays beautiful, and Wilde’s novel was used against him in court.'],
    ['Cyberpunk', 'William Gibson coined ‘cyberspace’ and wrote Neuromancer on a typewriter.'],
    ['The Canterbury Tales', 'Chaucer’s pilgrims tell tales ranging from saintly legend to fart jokes, a portrait of all of medieval England.'],
    ['Metafiction', 'Italo Calvino’s If on a winter’s night a traveller is a novel about you trying to read a novel.'],
    ['Gothic Fiction', 'Haunted castles, sinister monks and mad scientists: the Gothic made fear a pleasure.'],
    ['Sappho’s Fragments', 'Most of Sappho’s poetry is lost; some survives only because it was used as mummy-wrapping papyrus.'],
    ['Don Quixote', 'Often called the first modern novel, it is about a man who read so many books he decided to live inside one.'],
    ['Dystopian Fiction', 'Zamyatin’s We (1921) inspired both Huxley and Orwell, and was banned in the Soviet Union for decades.'],
    ['Lipograms and Constraints', 'Constraint can be a creative engine: the sonnet’s 14 lines have produced some of the freest poems ever written.'],
    ['Beowulf', 'An Old English poem preserved in a single manuscript that was scorched in a 1731 library fire.'],
    ['The Mahabharata', 'Roughly ten times the length of the Iliad and Odyssey combined, and it contains the Bhagavad Gita.'],
  ],
  Mathematics: [
    ['Gödel’s Incompleteness Theorems', 'Any consistent system rich enough for arithmetic contains true statements it can never prove.'],
    ['The Monty Hall Problem', 'Always switch doors: it doubles your odds, a fact that infuriated thousands of mathematicians in 1990.'],
    ['Fractals', 'A coastline gets longer the smaller your ruler, and fractals let shapes have dimensions like 1.26.'],
    ['The Golden Ratio', 'Phi turns up in sunflower spirals, though many claims about the Parthenon and Mona Lisa are myths.'],
    ['Infinity of Infinities', 'Cantor proved some infinities are bigger than others: there are more real numbers than whole numbers.'],
    ['The Banach-Tarski Paradox', 'Using the axiom of choice, you can cut a ball into finitely many pieces and reassemble them into two identical balls.'],
    ['Euler’s Identity', 'e^(iπ) + 1 = 0 ties together five of the most important numbers in one line.'],
    ['The Riemann Hypothesis', 'A million-dollar unsolved problem about where the zeros of one function lie, and the secret music of the primes.'],
    ['The Birthday Paradox', 'In a room of just 23 people, there is a better-than-even chance two share a birthday.'],
    ['Möbius Strip', 'A loop with a half-twist has only one side and one edge; cut it down the middle and it stays in one piece.'],
    ['The Seven Bridges of Königsberg', 'Euler proved you cannot cross all seven bridges exactly once, and invented graph theory doing it.'],
    ['Benford’s Law', 'In many real datasets, about 30% of numbers start with 1, a pattern used to catch fraud.'],
    ['Zero', 'Brahmagupta wrote rules for zero as a number in 628 CE, an idea Europe resisted for centuries.'],
    ['Pi', 'People have memorised over 70,000 digits of a number that never repeats or ends.'],
    ['The Four Colour Theorem', 'Any map needs only four colours; the 1976 proof was the first major theorem checked by computer.'],
    ['Fermat’s Last Theorem', 'Fermat scribbled that he had a proof too large for the margin; it took 358 years and Andrew Wiles to find one.'],
    ['Penrose Tiling', 'Tiles that cover a plane forever without ever repeating, later found echoed in real ‘quasicrystals’.'],
    ['The Collatz Conjecture', 'Halve evens, triple-and-add-one odds: every number seems to fall to 1, and no one can prove it.'],
    ['Topology', 'To a topologist, a coffee mug and a doughnut are the same shape.'],
    ['Prime Numbers', 'Cicadas emerge in 13- or 17-year cycles, prime intervals that may help them dodge predators.'],
    ['Imaginary Numbers', 'The square root of minus one started as a mathematical embarrassment and now runs electrical engineering.'],
    ['The Hairy Ball Theorem', 'You can never comb a hairy ball flat, which is why there is always somewhere on Earth with no wind.'],
    ['Kolmogorov Complexity', 'The complexity of a string is the length of the shortest program that prints it; most strings are incompressible.'],
    ['Ramsey Theory', 'Complete disorder is impossible: in any party of six, there are three mutual friends or three mutual strangers.'],
    ['The Mandelbrot Set', 'A one-line formula generates a boundary of infinite intricacy you can zoom into forever.'],
    ['Bayes’ Theorem', 'How to update your beliefs with evidence, and why a positive test for a rare disease is often a false alarm.'],
    ['The Halting Problem', 'Turing proved no program can decide, for every program, whether it will eventually stop.'],
    ['Srinivasa Ramanujan', 'A largely self-taught clerk from Madras sent formulas to Cambridge that Hardy said must be true because no one could invent them.'],
  ],
  'Economics & Game Theory': [
    ['Prisoner’s Dilemma', 'Two rational prisoners each betray the other and both end up worse off than if they had trusted.'],
    ['Tragedy of the Commons', 'Shared resources get overused when each person gains individually, though Elinor Ostrom showed communities often solve it.'],
    ['Nash Equilibrium', 'A state where no player can do better by changing strategy alone, even if everyone could do better together.'],
    ['The Cobra Effect', 'A bounty on dead cobras allegedly led people to breed cobras, a parable of incentives backfiring.'],
    ['Goodhart’s Law', 'When a measure becomes a target, it ceases to be a good measure.'],
    ['Veblen Goods', 'Some luxury goods sell more when their price goes up, because the price is the point.'],
    ['Opportunity Cost', 'The real cost of anything is the best alternative you gave up to get it.'],
    ['The Lindy Effect', 'For non-perishable things like books and ideas, every year they survive suggests a longer future.'],
    ['Tit for Tat', 'In Axelrod’s tournaments, the simplest strategy, cooperate then copy your opponent, beat far cleverer programs.'],
    ['Hyperinflation in Weimar Germany', 'In 1923 prices doubled every few days, and children built kites out of worthless banknotes.'],
    ['The Invisible Hand', 'Adam Smith used the famous phrase only a handful of times, and not quite how it is quoted today.'],
    ['Sunk Cost Fallacy', 'We keep pouring money into a failing project because of what we already spent, which is gone either way.'],
    ['The Ultimatum Game', 'People reject ‘unfair’ splits of free money, choosing nothing over being insulted.'],
    ['Network Effects', 'A telephone is useless alone and priceless when everyone has one.'],
    ['Moral Hazard', 'When you are insured against risk, you may take more of it.'],
    ['The Keynesian Beauty Contest', 'Keynes compared markets to judging not who is prettiest, but who others will think others will think is prettiest.'],
    ['Loss Aversion', 'Losing $100 feels roughly twice as bad as winning $100 feels good.'],
    ['Schelling Points', 'Asked to meet a stranger in New York with no plan, many people choose Grand Central at noon.'],
    ['The Paradox of Thrift', 'If everyone saves more in a recession, total spending falls and everyone may end up with less.'],
    ['Creative Destruction', 'Schumpeter saw capitalism as a gale that constantly destroys old industries to create new ones.'],
    ['The Market for Lemons', 'If buyers can’t tell good used cars from bad, good sellers leave and the market fills with lemons.'],
    ['Gift Economies', 'In some societies wealth is measured not by what you keep but by the web of obligations you have created.'],
    ['The Diamond-Water Paradox', 'Water is essential and cheap, diamonds useless and expensive, until you think about the value of the next unit.'],
    ['Mechanism Design', 'Reverse game theory: design the rules so that selfish players produce the outcome you want.'],
    ['The Big Mac Index', 'The Economist compares burger prices worldwide as a tongue-in-cheek test of currency valuation.'],
    ['Pareto Principle', 'Roughly 80% of effects come from 20% of causes, an idea Pareto drew from Italian land ownership.'],
    ['Braess’s Paradox', 'Adding a new road to a network can make traffic worse for everyone.'],
    ['Universal Basic Income', 'Experiments from Finland to Kenya test what happens when people get money with no strings attached.'],
  ],
  'Architecture & Design': [
    ['Brutalist Architecture', 'Named from the French béton brut, raw concrete, these monoliths are loathed, beloved and increasingly rescued.'],
    ['The Bauhaus', 'A German art school that lasted only 14 years shaped almost every chair, font and kitchen around you.'],
    ['Hagia Sophia', 'Its dome seems to float on a ring of light, and for nearly a thousand years it was the largest cathedral on Earth.'],
    ['Gaudí’s Sagrada Família', 'Begun in 1882 and still not finished, Gaudí designed its arches using hanging chain models flipped upside down.'],
    ['Feng Shui', 'An ancient Chinese practice of arranging space to harmonise with the flow of qi.'],
    ['Kowloon Walled City', 'Once the densest place on Earth, it housed tens of thousands in a lawless block of buildings grown together.'],
    ['Stepwells of India', 'Rani ki Vav descends seven storeys of carved stone to reach water, a temple turned upside down.'],
    ['Geodesic Domes', 'Buckminster Fuller’s triangulated domes get stronger relative to weight the larger they become.'],
    ['Swiss Style Typography', 'Helvetica, grids and objective clarity: the International Typographic Style made design feel like engineering.'],
    ['Metabolism (Architecture)', 'Tokyo’s Nakagin Capsule Tower had pods meant to be swapped like cells; it was demolished in 2022.'],
    ['Dieter Rams’ Ten Principles', '‘Less, but better’: a Braun designer’s rules that you can see echoed in many modern gadgets.'],
    ['Hostile Architecture', 'Spikes, slanted benches and armrests in odd places are design choices aimed at people.'],
    ['Islamic Geometric Patterns', 'Craftsmen built star patterns from compass and straightedge that anticipate mathematical quasicrystals.'],
    ['Gothic Cathedrals', 'Flying buttresses let walls dissolve into stained glass, turning stone buildings into lanterns.'],
    ['Biophilic Design', 'Hospital patients with a view of trees have been found to recover faster than those facing a brick wall.'],
    ['Petra', 'The Nabataeans carved a city into rose-red cliffs and engineered water channels through the desert.'],
    ['Skeuomorphism', 'Early iPhone apps imitated leather and torn paper; the ‘save’ icon still shows a floppy disk.'],
    ['The Panopticon', 'Bentham designed a prison where inmates can always be watched but never know when, and Foucault saw society in it.'],
    ['Japanese Joinery', 'Master carpenters lock beams together with intricate wooden joints and no nails or glue.'],
    ['Le Corbusier’s Radiant City', 'A dream of towers in parks that inspired real housing projects, some of which became cautionary tales.'],
    ['Desire Paths', 'The dirt tracks people wear across lawns are honest feedback about where the paths should have been.'],
    ['Wayfinding Design', 'Harry Beck’s 1933 London Tube map ignored geography entirely and became a design icon.'],
    ['Art Nouveau', 'Whiplash curves, dragonflies and iron lilies: Paris metro entrances still bloom with Guimard’s design.'],
    ['Tensegrity', 'Structures where rigid struts float in a web of tension cables, never touching one another.'],
    ['Earthships', 'Off-grid homes built from tyres, bottles and earth that heat, cool and water themselves.'],
    ['The Golden Gate Bridge’s Colour', '‘International Orange’ was meant to be a primer but was kept because it suited the fog.'],
    ['Persian Gardens (Chahar Bagh)', 'A walled garden divided into four by water channels, the original idea behind the word ‘paradise’.'],
    ['Wind Catchers (Badgirs)', 'Towers in Yazd and across the Gulf funnel breezes down to cool houses without electricity.'],
  ],
  'Religion & Myth': [
    ['Trickster Gods', 'Loki, Anansi, Coyote and Hermes break rules, steal fire and invent things the gods didn’t want us to have.'],
    ['Gnosticism', 'Some Gnostics believed the world was made by a lesser, ignorant god, and salvation meant secret knowledge.'],
    ['The Norse Ragnarök', 'In Norse myth even the gods die, the world sinks into the sea, and then a green earth rises again.'],
    ['The Dreaming', 'In many Aboriginal Australian traditions, ancestral beings shaped the land, and that time is ongoing.'],
    ['Sufi Whirling', 'Mevlevi dervishes spin in meditation, one palm up to receive from heaven, one down to give to earth.'],
    ['The Golem', 'In Jewish legend, Rabbi Loew of Prague shaped a clay protector and animated it with a sacred word.'],
    ['Zen Koans', '‘What is the sound of one hand clapping?’ Koans are puzzles meant to break the reasoning mind open.'],
    ['Ouroboros', 'The serpent eating its own tail appears from ancient Egypt to alchemy, a symbol of eternal cycles.'],
    ['The Bardo Thödol', 'The Tibetan Book of the Dead guides consciousness through 49 days between death and rebirth.'],
    ['Orphism', 'An ancient Greek mystery cult taught that the soul is divine and imprisoned in the body, awaiting release.'],
    ['Kami and Shinto', 'In Shinto, kami can inhabit mountains, waterfalls, ancient trees and even skilled craftsmen’s tools.'],
    ['The Flood Myth', 'Utnapishtim, Noah, Manu and Deucalion: stories of a world-drowning flood appear across continents.'],
    ['Animism', 'The view that rivers, animals and stones have spirits may be the oldest religious outlook humans have.'],
    ['The Eleusinian Mysteries', 'For nearly 2,000 years initiates kept the secret of what happened at Eleusis, and we still don’t know.'],
    ['Dharma', 'In Hindu thought, dharma is your duty, your nature and the cosmic order, all at once.'],
    ['Taoism and Wu Wei', 'The Tao Te Ching praises water: soft and yielding, yet it wears away stone. Act without forcing.'],
    ['The Mayan Popol Vuh', 'The gods made humans from mud, then wood, then finally maize, after the first attempts failed.'],
    ['Yoruba Orishas', 'Yoruba deities like Ṣàngó and Ọ̀ṣun travelled with enslaved people and live on in Santería and Candomblé.'],
    ['The Book of Job', 'A righteous man loses everything and demands an answer; God replies with a whirlwind of questions.'],
    ['Mithraism', 'A secret Roman cult met in underground cave-temples centred on an image of a god slaying a bull.'],
    ['Indra’s Net', 'A Buddhist image of an infinite net with a jewel at every knot, each reflecting all the others.'],
    ['The Wild Hunt', 'Across European folklore, a ghostly troop of riders thunders across the winter sky.'],
    ['Zoroastrianism', 'One of the oldest living faiths framed the cosmos as a battle between truth and the lie.'],
    ['Anansi the Spider', 'The Akan trickster won all the world’s stories from the sky god by outwitting a python, a leopard and hornets.'],
    ['Kabbalah’s Tree of Life', 'Ten sefirot connected by 22 paths map how the infinite flows into the finite world.'],
    ['Cosmic Egg Myths', 'From the Hindu Hiranyagarbha to the Chinese Pangu, many cultures imagine the universe hatching.'],
    ['Persephone', 'Six pomegranate seeds bound the goddess to the underworld for part of each year, and so we have winter.'],
    ['Jainism and Ahimsa', 'Some Jain monks sweep the path before them to avoid stepping on insects.'],
  ],
  Technology: [
    ['The Turing Test', 'Turing proposed replacing ‘Can machines think?’ with a party game about telling human from machine.'],
    ['Ada Lovelace’s Notes', 'In 1843 Lovelace imagined Babbage’s engine might compose music, a century before computers existed.'],
    ['The Jacquard Loom', 'Punched cards controlled weaving patterns in 1804, and later controlled computers.'],
    ['Moore’s Law', 'An observation in 1965 that transistor counts double regularly became a self-fulfilling industry roadmap.'],
    ['Public-Key Cryptography', 'You can lock a message with a key anyone can have, that only your secret key can open.'],
    ['The Y2K Bug', 'Saving two digits of memory per date nearly broke the world, and a huge effort meant it mostly didn’t.'],
    ['ARPANET', 'The first message over the internet’s ancestor in 1969 was meant to be ‘LOGIN’; the system crashed after ‘LO’.'],
    ['Open Source', 'Linux began as a student’s hobby project and now runs most of the world’s servers and phones.'],
    ['The Mechanical Turk', 'A chess-playing automaton toured Europe in the 1700s, beating Napoleon, with a human hidden inside.'],
    ['Blockchain', 'A ledger that thousands of strangers keep in sync with no one in charge, born from a pseudonymous paper.'],
    ['The Clock of the Long Now', 'A clock being built inside a Texas mountain is designed to tick for 10,000 years.'],
    ['Conway’s Game of Life', 'Four simple rules on a grid generate gliders, guns and even a working computer.'],
    ['Lenna and Test Images', 'A cropped 1972 magazine photo became the standard image for testing compression for decades.'],
    ['The Phonautograph', 'In 1860 a Frenchman recorded sound as squiggles he could not play back; in 2008 scientists finally did.'],
    ['Steganography', 'Hiding a message inside an image or a song, so no one knows a message exists at all.'],
    ['The Enigma Machine', 'Bletchley Park cracked the Nazi cipher machine, helped by one flaw: no letter could encrypt to itself.'],
    ['Solarpunk', 'A movement imagining futures with green tech, community and art nouveau aesthetics instead of dystopia.'],
    ['Moonbounce Radio', 'Amateur radio operators bounce signals off the Moon to chat with each other across the planet.'],
    ['Lisp', 'Created in 1958, Lisp treats code as data, and its descendants still teach programmers to think differently.'],
    ['The Uncanny Valley', 'Robots become more likeable as they look more human, until they get almost right and become creepy.'],
    ['Digital Archaeology', 'NASA engineers have had to hunt down obsolete tape drives to read 1960s mission data.'],
    ['The Haber-Bosch Process', 'Making fertiliser from air feeds roughly half the people alive today.'],
    ['Error-Correcting Codes', 'Scratched CDs still play and Voyager still phones home thanks to clever redundancy maths.'],
    ['Cybernetics', 'Norbert Wiener’s science of feedback loops linked thermostats, nervous systems and societies.'],
    ['The Long Tail', 'The internet made it profitable to sell millions of niche items a few times each.'],
    ['The Unix Philosophy', 'Unix’s ‘do one thing well’ tools from the 1970s still glue modern computing together.'],
    ['Voyager Golden Record', 'A gold-plated record carries whale song, a kiss and Chuck Berry out of the solar system.'],
    ['Right to Repair', 'Farmers have hacked their own tractors to get around software locks on repairs.'],
  ],
  'Nature & Biology': [
    ['Mycelium Networks', 'Fungal threads link tree roots and can move nutrients between plants, though the ‘wood wide web’ is debated.'],
    ['Bioluminescence', 'Most deep-sea animals make their own light, using it to hunt, hide and flirt in the dark.'],
    ['Octopus Intelligence', 'Most of an octopus’s neurons are in its arms, which can taste and react independently.'],
    ['The Immortal Jellyfish', 'Turritopsis dohrnii can revert to its juvenile stage when stressed, potentially cycling indefinitely.'],
    ['Slime Molds', 'A brainless single cell can find the shortest path through a maze and redraw Tokyo’s rail network.'],
    ['Murmurations', 'Thousands of starlings move as one, each bird tracking just its seven nearest neighbours.'],
    ['Cordyceps', 'This fungus hijacks insects, steering them to the perfect spot before sprouting from their heads.'],
    ['Axolotls', 'These Mexican salamanders can regrow limbs, parts of their heart and even portions of their brain.'],
    ['Crows’ Funerals', 'Crows gather around their dead, possibly to learn about danger in that place.'],
    ['Symbiosis', 'Every cell in your body contains mitochondria, descendants of bacteria that moved in two billion years ago.'],
    ['Whale Fall', 'When a whale dies and sinks, its carcass can feed an entire deep-sea ecosystem for decades.'],
    ['The Wood Frog', 'In winter it freezes solid, its heart stops, and in spring it thaws and hops away.'],
    ['Mantis Shrimp', 'Its club strikes with the acceleration of a bullet, and its eyes have up to 16 types of photoreceptors.'],
    ['Pando', 'A single quaking aspen clone in Utah has tens of thousands of trunks and may be one of the heaviest organisms on Earth.'],
    ['Animal Migration and Magnetoreception', 'Birds may literally see Earth’s magnetic field using quantum effects in their eyes.'],
    ['Horizontal Gene Transfer', 'Bacteria swap genes like trading cards, which is how antibiotic resistance spreads so fast.'],
    ['The Naked Mole-Rat', 'Nearly cancer-resistant, able to survive minutes without oxygen, and living in colonies with a queen.'],
    ['Carnivorous Plants', 'A Venus flytrap counts: it snaps shut only when a trigger hair is touched twice within about 20 seconds.'],
    ['Elephant Communication', 'Elephants rumble at frequencies below human hearing that can travel kilometres through the ground.'],
    ['Convergent Evolution', 'Crabs have evolved so many times that ‘carcinisation’ is a running joke among biologists.'],
    ['Lichen', 'A partnership of fungus and algae (sometimes plus a yeast) that can live on bare rock for centuries.'],
    ['Plant Signalling', 'Tomato plants under attack release airborne chemicals that prime their neighbours’ defences.'],
    ['The Gut Microbiome', 'You host trillions of microbes, and they may influence your mood, weight and immune system.'],
    ['Lyrebirds', 'Australia’s lyrebird can mimic chainsaws, camera shutters and dozens of other birds perfectly.'],
    ['Eusociality', 'Ant colonies behave like a superorganism, with farming, warfare and living bridges.'],
    ['Cephalopod Camouflage', 'Cuttlefish change colour and texture in milliseconds, possibly while colour-blind.'],
    ['Bdelloid Rotifers', 'Microscopic animals that have apparently lived without males for millions of years.'],
    ['Deep-Sea Hydrothermal Vents', 'Ecosystems powered by chemicals instead of sunlight may hint at how life began.'],
  ],
  Language: [
    ['The Sapir-Whorf Hypothesis', 'Does the language you speak shape how you think? Strong versions are rejected, weak ones keep turning up evidence.'],
    ['Untranslatable Words', 'German Waldeinsamkeit is the feeling of being alone in the woods; Japanese komorebi, sunlight through leaves.'],
    ['Pirahã', 'This Amazonian language reportedly lacks exact number words, sparking fierce debates about universal grammar.'],
    ['Esperanto', 'Invented in 1887 to unite humanity, Esperanto has native speakers born to Esperanto-speaking parents.'],
    ['Whistled Languages', 'On La Gomera in the Canary Islands, Silbo Gomero turns Spanish into whistles that carry across valleys.'],
    ['The Great Vowel Shift', 'Between about 1400 and 1700, English vowels moved so much that spelling got stuck in the past.'],
    ['Linear A', 'The Minoan script has been studied for over a century and remains undeciphered.'],
    ['Pidgins and Creoles', 'Children exposed to a rough pidgin turn it into a full, grammatical creole within a generation.'],
    ['Nicaraguan Sign Language', 'Deaf children brought together in the 1970s invented a complete new language before linguists’ eyes.'],
    ['Evidentiality', 'In some languages you must mark grammatically whether you saw something yourself or heard it secondhand.'],
    ['Proto-Indo-European', 'Linguists reconstructed a language no one wrote down, the ancestor of English, Hindi, Persian and Russian.'],
    ['Click Consonants', 'Languages of southern Africa such as Xhosa use clicks as everyday consonants.'],
    ['Linguistic Relativity of Colour', 'Russian has separate basic words for light blue and dark blue, and speakers distinguish them slightly faster.'],
    ['Constructed Languages', 'Tolkien invented languages first and wrote Middle-earth partly to give them speakers.'],
    ['Semantic Change', '‘Nice’ once meant foolish, and ‘silly’ once meant blessed.'],
    ['Tone Languages', 'In Mandarin, ‘ma’ can mean mother, hemp, horse or scold depending on the pitch.'],
    ['The Rebus Principle', 'Writing systems often grow by using a picture for its sound, like drawing a bee and a leaf for ‘belief’.'],
    ['Code-Switching', 'Bilingual speakers swap languages mid-sentence following subtle grammatical rules.'],
    ['Kennings', 'Old Norse poets called the sea the ‘whale-road’ and blood the ‘battle-sweat’.'],
    ['Dead Languages Revived', 'Hebrew went from mostly liturgical to the everyday language of millions within about a century.'],
    ['Phonaesthesia', 'Across languages, people match the nonsense word ‘bouba’ to round shapes and ‘kiki’ to spiky ones.'],
    ['Euphemism Treadmill', 'Polite words for taboo things become taboo themselves and need replacing, again and again.'],
    ['Cuneiform', 'The first writing began with accountants pressing wedge marks into clay to count sheep and barley.'],
    ['Lost Positives', 'English has ‘disgruntled’, ‘unkempt’ and ‘inept’, but rarely the gruntled, kempt or ept.'],
    ['Hangul', 'King Sejong designed the Korean alphabet in the 1440s so letters even depict how the mouth makes sounds.'],
    ['Grammatical Gender', 'In German the moon is masculine and the sun feminine; in French it is the other way round.'],
    ['The Ithkuil Language', 'A constructed language designed to express thoughts with extreme precision and brevity.'],
    ['Palindromes and Wordplay', '‘A man, a plan, a canal: Panama’ is a palindrome, a sentence that reads the same in reverse.'],
  ],
}

export const TOPICS: Topic[] = CATEGORIES.flatMap((category) =>
  [...RAW[category], ...(MORE_TOPICS[category] ?? [])].map(([name, hook]) => ({ name, category, hook })),
)

const BY_NAME = new Map(TOPICS.map((t) => [t.name, t]))

export function findTopic(name: string): Topic | undefined {
  return BY_NAME.get(name)
}

/** Tiny string hash (FNV-1a) → 32-bit unsigned. */
function hash(str: string): number {
  let h = 0x811c9dc5
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i)
    h = Math.imul(h, 0x01000193)
  }
  return h >>> 0
}

/** Deterministic topic for a 'YYYY-MM-DD' day key. Same key, same topic, everywhere. */
export function topicOfTheDay(dayKey: string): Topic {
  return TOPICS[hash('lab:' + dayKey) % TOPICS.length]
}
